<%@ Page Language="VB" AutoEventWireup="false" CodeFile="input_empl_2.aspx.vb" Inherits="modules_hr_input_empl_2" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head id="Head1" runat="server">
    <title>Untitled Page</title>
    <link href="../../../StyleSheet.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <form id="form1" runat="server">
    <div>
        <table border="0" width="100%">
            <tr>
                <td colspan="2">
						<asp:Label ID="lblHeader" runat="server" Font-Bold="True" Font-Size="Small" 
                        Text=":: Edit Employment History"></asp:Label></td>
            </tr>
            <tr>
                <td width="3%">&nbsp;
                    </td>
                <td>
        <asp:GridView ID="gvMaster" runat="server" CssClass="noBorderedMenuTable" AutoGenerateColumns="False" 
                    DataKeyNames="StaffId" DataSourceID="dsoUsers" AllowSorting="True" 
                    CellPadding="4" ForeColor="#333333" GridLines="None" Width="1000px" 
                        SelectedIndex="0" PageSize="50" 
                        
                        
                        EmptyDataText="&lt;br /&gt;&lt;br /&gt;No staff records found&lt;br /&gt;&lt;br /&gt;&amp;nbsp;" 
                        EnableModelValidation="True" >
            <Columns>
                <asp:TemplateField HeaderText="Staff Code" SortExpression="StaffCode">
                    <EditItemTemplate>
                        <asp:Label ID="TextBox47" runat="server" Text='<%# Bind("StaffCode") %>'></asp:Label>
                   </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label49" runat="server" Text='<%# Bind("StaffCode") %>'></asp:Label>
                    </ItemTemplate>
                    <ItemStyle Width="70px" />
                </asp:TemplateField>
                <asp:TemplateField>
                    <ItemTemplate>
                        <asp:Image ID="Image1" runat="server" Height="30px" 
                        ImageUrl='<%# "~\images\pp_staff\" & Databinder.Eval(Container.DataItem, "StaffCode").ToString & ".jpg" %>' 
                        Width="30px" BorderColor="Black" BorderStyle="Solid" BorderWidth="2px" /><br /><asp:Label ID="Label49_2" runat="server" Text='<%# Databinder.Eval(Container.DataItem, "Surname").ToString.ToUpper & " " & Databinder.Eval(Container.DataItem, "OtherNames").ToString.ToUpper %>'></asp:Label>
                    </ItemTemplate>
                    <ItemStyle Width="60px" />
                </asp:TemplateField>
                <asp:CommandField SelectText="Show Employment History" ShowSelectButton="True">
                <ItemStyle Width="80px" />
                </asp:CommandField>
                <asp:TemplateField HeaderText="EMPLOYMENT HISTORY">
                    <ItemTemplate>
                        <asp:GridView ID="gvDetail" runat="server" AutoGenerateColumns="False" 
                            AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
                            AutoGenerateSelectButton="True" CellPadding="4" CssClass="noBorderedMenuTable" 
                            DataKeyNames="StaffEmploymentId" DataSourceID="dsSqlGetDetail" 
                            EmptyDataText="&amp;nbsp;&lt;br /&gt;No records to display.&lt;br /&gt;&amp;nbsp;" 
                            ForeColor="#333333" GridLines="None" Visible="False" Width="100%" 
                            Font-Bold="False">
                            <Columns>
                                <asp:BoundField DataField="StaffEmploymentId" HeaderText="Id" 
                                    InsertVisible="False" ReadOnly="True" SortExpression="StaffEmploymentId" />
                                <asp:TemplateField HeaderText="Staff Id" SortExpression="StaffId">
                                    <EditItemTemplate>
                                        <asp:Label ID="Label10" runat="server" Text='<%# Bind("StaffId") %>'></asp:Label>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="Label1" runat="server" Text='<%# Bind("StaffId") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Employer" SortExpression="EmployerName">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="TextBox2" runat="server" Columns="20" 
                                            Text='<%# Bind("EmployerName") %>'></asp:TextBox>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="Label2" runat="server" Text='<%# Bind("EmployerName") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Address" 
                                    SortExpression="EmployerAddress">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="TextBox3" runat="server" Columns="20" 
                                            CssClass="defaultFormElementStyle" Rows="3" 
                                            Text='<%# Bind("EmployerAddress") %>' TextMode="MultiLine"></asp:TextBox>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="Label3" runat="server" Text='<%# Bind("EmployerAddress") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Start" SortExpression="StartDate">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="TextBox4" runat="server" Columns="10" 
                                            Text='<%# Bind("StartDate") %>'></asp:TextBox>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="Label4" runat="server" 
                                            Text='<%# Common.GetFriendlyDateShort(CType(DataBinder.Eval(Container.DataItem,"StartDate"), Date)) %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="End" SortExpression="EndDate">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="TextBox5" runat="server" Columns="10" 
                                            Text='<%# Bind("EndDate") %>'></asp:TextBox>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="Label5" runat="server" 
                                            Text='<%# Common.GetFriendlyDateShort(CType(DataBinder.Eval(Container.DataItem, "EndDate"), Date)) %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Duration">
                                    <ItemTemplate>
                                        <asp:Label ID="Label11" runat="server" 
                                            Text='<%# Common.GetTimespanInMonths(CType(Databinder.Eval(Container.DataItem, "StartDate"), Date), CType(Databinder.Eval(Container.DataItem, "EndDate"), Date)).ToString & "m" %>'></asp:Label>
                                    </ItemTemplate>
                                    <HeaderStyle HorizontalAlign="Right" />
                                    <ItemStyle HorizontalAlign="Right" />
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Exit Reason" SortExpression="ExitReason">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="TextBox6" runat="server" Columns="20" 
                                            Text='<%# Bind("ExitReason") %>'></asp:TextBox>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="Label6" runat="server" Text='<%# Bind("ExitReason") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Last Pay" SortExpression="LastPay">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="TextBox7" runat="server" Columns="10" 
                                            CssClass="defaultFormElementStyleRightAligned" Text='<%# Bind("LastPay") %>'></asp:TextBox>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        N
                                        <asp:Label ID="Label7" runat="server" 
                                            Text='<%# FormatNumber(Databinder.Eval(Container.DataItem,"LastPay"), 0) %>'></asp:Label>
                                    </ItemTemplate>
                                    <HeaderStyle HorizontalAlign="Right" />
                                    <ItemStyle HorizontalAlign="Right" />
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Contact" 
                                    SortExpression="Reference">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="TextBox8" runat="server" Columns="20" 
                                            Text='<%# Bind("Reference") %>'></asp:TextBox>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="Label8" runat="server" Text='<%# Bind("Reference") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:BoundField DataField="Remark" HeaderText="Remark" SortExpression="Remark" 
                                    Visible="False" />
                            </Columns>
                            <RowStyle BackColor="#FFFBD6" ForeColor="#333333" HorizontalAlign="Left" 
                                VerticalAlign="Top" />
                            <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" 
                                HorizontalAlign="Left" VerticalAlign="Top" />
                            <EditRowStyle CssClass="defaultFormElementStyle" />
                            <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                            <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
                            <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="Navy" />
                            <AlternatingRowStyle BackColor="White" />
                        </asp:GridView>
                   <br />
                        <asp:Label ID="lblAddNew" runat="server" Font-Bold="True" Font-Size="Small" 
                        Text=":: Add a Previous Employment" CssClass="defaultHeaderTextStyle" 
                            Visible="False"></asp:Label>
                        <asp:DetailsView ID="DetailsView1" runat="server" 
                            AutoGenerateInsertButton="True" AutoGenerateRows="False" CellPadding="4" 
                            DataKeyNames="StaffEmploymentId" DataSourceID="dsSqlGetDetail" DefaultMode="Insert" 
                            ForeColor="#333333" GridLines="None" Visible="False" Width="100%" 
                            Font-Bold="False" OnItemInserted="DetailsViewItemInserted">
                            <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                            <CommandRowStyle BackColor="#FFFFC0" Font-Bold="True" />
                            <RowStyle BackColor="#FFFBD6" ForeColor="#333333" HorizontalAlign="Left" 
                                VerticalAlign="Middle" Wrap="True" />
                            <FieldHeaderStyle BackColor="#FFFF99" Font-Bold="True" VerticalAlign="Top" 
                                Width="220px" />
                            <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
                            <Fields>
                                <asp:BoundField DataField="StaffEmploymentId" HeaderText="StaffEmploymentId" 
                                    InsertVisible="False" ReadOnly="True" SortExpression="StaffEmploymentId" />
                                <asp:TemplateField HeaderText="Staff Concerned:" SortExpression="StaffId">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="TextBox1" runat="server" Text='<%# Bind("StaffId") %>'></asp:TextBox>
                                    </EditItemTemplate>
                                    <InsertItemTemplate>
                                        <asp:DropDownList ID="DropDownList5" runat="server" 
                                            CssClass="defaultFormElementStyle" DataSourceID="dsSqlGetSingleStaff" 
                                            DataTextField="StaffDetails" DataValueField="StaffId" 
                                            SelectedValue='<%# Bind("StaffId") %>'>
                                        </asp:DropDownList>
                                        <asp:SqlDataSource ID="dsSqlGetSingleStaff" runat="server" 
                                            ConnectionString="<%$ ConnectionStrings:iTecon %>" 
                                            SelectCommand="SELECT [StaffId], UPPER([Surname]) + ' ' + UPPER([OtherNames]) + ' | ' + UPPER([StaffCode]) + ' | (' + UPPER(b.[DepartmentName]) + ' Department)' AS StaffDetails FROM [HR_Staff_Base] a INNER JOIN [Core_Department] b ON a.Department = b.DepartmentCode WHERE StaffId = @StaffId">
                                            <SelectParameters>
                                                <asp:ControlParameter ControlID="gvMaster" Name="StaffId" 
                                                    PropertyName="SelectedValue" />
                                            </SelectParameters>
                                        </asp:SqlDataSource>
                                    </InsertItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="Label12" runat="server" Text='<%# Bind("StaffId") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Name of Previous Employer:" 
                                    SortExpression="EmployerName">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="TextBox12" runat="server" 
                                            Text='<%# Bind("EmployerAddress") %>'></asp:TextBox>
                                    </EditItemTemplate>
                                    <InsertItemTemplate>
                                        <asp:TextBox ID="TextBox13" runat="server" Columns="50" 
                                            Text='<%# Bind("EmployerAddress") %>' CssClass="defaultFormElementStyle" 
                                            Rows="5" TextMode="MultiLine"></asp:TextBox>
                                    </InsertItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="Label14" runat="server" Text='<%# Bind("EmployerAddress") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Address of Previous Employer:" 
                                    SortExpression="EmployerAddress">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="TextBox10" runat="server" Text='<%# Bind("EmployerName") %>'></asp:TextBox>
                                    </EditItemTemplate>
                                    <InsertItemTemplate>
                                        <asp:TextBox ID="TextBox11" runat="server" Columns="40" 
                                            Text='<%# Bind("EmployerName") %>'></asp:TextBox>
                                    </InsertItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="Label13" runat="server" Text='<%# Bind("EmployerName") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Start Date:" SortExpression="StartDate">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="TextBox15" runat="server" Text='<%# Bind("EndDate") %>'></asp:TextBox>
                                    </EditItemTemplate>
                                    <InsertItemTemplate>
                                    <asp:DropDownList ID="ddlDateStart_Month" runat="server" AutoPostBack="True" 
                                        CssClass="defaultFormElementStyle">
                                        <asp:ListItem Value="1">January</asp:ListItem>
                                        <asp:ListItem Value="2">February</asp:ListItem>
                                        <asp:ListItem Value="3">March</asp:ListItem>
                                        <asp:ListItem Value="4">April</asp:ListItem>
                                        <asp:ListItem Value="5">May</asp:ListItem>
                                        <asp:ListItem Value="6">June</asp:ListItem>
                                        <asp:ListItem Value="7">July</asp:ListItem>
                                        <asp:ListItem Value="8">August</asp:ListItem>
                                        <asp:ListItem Value="9">September</asp:ListItem>
                                        <asp:ListItem Value="10">October</asp:ListItem>
                                        <asp:ListItem Value="11">November</asp:ListItem>
                                        <asp:ListItem Value="12">December</asp:ListItem>
                                    </asp:DropDownList>
                                    <asp:DropDownList ID="ddlDateStart_Day" runat="server" AutoPostBack="True" 
                                        CssClass="defaultFormElementStyle">
                                        <asp:ListItem value="1">1</asp:ListItem>
                                        <asp:ListItem value="2">2</asp:ListItem>
                                        <asp:ListItem value="3">3</asp:ListItem>
                                        <asp:ListItem value="4">4</asp:ListItem>
                                        <asp:ListItem value="5">5</asp:ListItem>
                                        <asp:ListItem value="6">6</asp:ListItem>
                                        <asp:ListItem value="7">7</asp:ListItem>
                                        <asp:ListItem value="8">8</asp:ListItem>
                                        <asp:ListItem value="9">9</asp:ListItem>
                                        <asp:ListItem value="10">10</asp:ListItem>
                                        <asp:ListItem value="11">11</asp:ListItem>
                                        <asp:ListItem value="12">12</asp:ListItem>
                                        <asp:ListItem value="13">13</asp:ListItem>
                                        <asp:ListItem value="14">14</asp:ListItem>
                                        <asp:ListItem value="15">15</asp:ListItem>
                                        <asp:ListItem value="16">16</asp:ListItem>
                                        <asp:ListItem value="17">17</asp:ListItem>
                                        <asp:ListItem value="18">18</asp:ListItem>
                                        <asp:ListItem value="19">19</asp:ListItem>
                                        <asp:ListItem value="20">20</asp:ListItem>
                                        <asp:ListItem value="21">21</asp:ListItem>
                                        <asp:ListItem value="22">22</asp:ListItem>
                                        <asp:ListItem value="23">23</asp:ListItem>
                                        <asp:ListItem value="24">24</asp:ListItem>
                                        <asp:ListItem value="25">25</asp:ListItem>
                                        <asp:ListItem value="26">26</asp:ListItem>
                                        <asp:ListItem value="27">27</asp:ListItem>
                                        <asp:ListItem value="28">28</asp:ListItem>
                                        <asp:ListItem value="29">29</asp:ListItem>
                                        <asp:ListItem value="30">30</asp:ListItem>
                                        <asp:ListItem value="31">31</asp:ListItem>
                                    </asp:DropDownList>
                                    <asp:DropDownList ID="ddlDateStart_Year" runat="server" AutoPostBack="True" 
                                        CssClass="defaultFormElementStyle" DataSourceID="dsObjYears">
                                    </asp:DropDownList>
                                        <asp:Label ID="lblStartDate" runat="server" Text='<%# Bind("StartDate") %>'></asp:Label>
                                    </InsertItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="Label16" runat="server" Text='<%# Bind("EndDate") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="End Date:" SortExpression="EndDate">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="TextBox14" runat="server" Text='<%# Bind("StartDate") %>'></asp:TextBox>
                                    </EditItemTemplate>
                                    <InsertItemTemplate>
                                    <asp:DropDownList ID="ddlDateEnd_Month" runat="server" AutoPostBack="True" 
                                        CssClass="defaultFormElementStyle">
                                        <asp:ListItem Value="1">January</asp:ListItem>
                                        <asp:ListItem Value="2">February</asp:ListItem>
                                        <asp:ListItem Value="3">March</asp:ListItem>
                                        <asp:ListItem Value="4">April</asp:ListItem>
                                        <asp:ListItem Value="5">May</asp:ListItem>
                                        <asp:ListItem Value="6">June</asp:ListItem>
                                        <asp:ListItem Value="7">July</asp:ListItem>
                                        <asp:ListItem Value="8">August</asp:ListItem>
                                        <asp:ListItem Value="9">September</asp:ListItem>
                                        <asp:ListItem Value="10">October</asp:ListItem>
                                        <asp:ListItem Value="11">November</asp:ListItem>
                                        <asp:ListItem Value="12">December</asp:ListItem>
                                    </asp:DropDownList>
                                    <asp:DropDownList ID="ddlDateEnd_Day" runat="server" AutoPostBack="True" 
                                        CssClass="defaultFormElementStyle">
                                        <asp:ListItem value="1">1</asp:ListItem>
                                        <asp:ListItem value="2">2</asp:ListItem>
                                        <asp:ListItem value="3">3</asp:ListItem>
                                        <asp:ListItem value="4">4</asp:ListItem>
                                        <asp:ListItem value="5">5</asp:ListItem>
                                        <asp:ListItem value="6">6</asp:ListItem>
                                        <asp:ListItem value="7">7</asp:ListItem>
                                        <asp:ListItem value="8">8</asp:ListItem>
                                        <asp:ListItem value="9">9</asp:ListItem>
                                        <asp:ListItem value="10">10</asp:ListItem>
                                        <asp:ListItem value="11">11</asp:ListItem>
                                        <asp:ListItem value="12">12</asp:ListItem>
                                        <asp:ListItem value="13">13</asp:ListItem>
                                        <asp:ListItem value="14">14</asp:ListItem>
                                        <asp:ListItem value="15">15</asp:ListItem>
                                        <asp:ListItem value="16">16</asp:ListItem>
                                        <asp:ListItem value="17">17</asp:ListItem>
                                        <asp:ListItem value="18">18</asp:ListItem>
                                        <asp:ListItem value="19">19</asp:ListItem>
                                        <asp:ListItem value="20">20</asp:ListItem>
                                        <asp:ListItem value="21">21</asp:ListItem>
                                        <asp:ListItem value="22">22</asp:ListItem>
                                        <asp:ListItem value="23">23</asp:ListItem>
                                        <asp:ListItem value="24">24</asp:ListItem>
                                        <asp:ListItem value="25">25</asp:ListItem>
                                        <asp:ListItem value="26">26</asp:ListItem>
                                        <asp:ListItem value="27">27</asp:ListItem>
                                        <asp:ListItem value="28">28</asp:ListItem>
                                        <asp:ListItem value="29">29</asp:ListItem>
                                        <asp:ListItem value="30">30</asp:ListItem>
                                        <asp:ListItem value="31">31</asp:ListItem>
                                    </asp:DropDownList>
                                    <asp:DropDownList ID="ddlDateEnd_Year" runat="server" AutoPostBack="True" 
                                        CssClass="defaultFormElementStyle" DataSourceID="dsObjYears">
                                    </asp:DropDownList>
                                         <asp:Label ID="lblEndDate" runat="server" Text='<%# Bind("EndDate") %>'></asp:Label>
                                   </InsertItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="Label15" runat="server" Text='<%# Bind("StartDate") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Reason For Exit:" SortExpression="ExitReason">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="TextBox16" runat="server" Text='<%# Bind("ExitReason") %>'></asp:TextBox>
                                    </EditItemTemplate>
                                    <InsertItemTemplate>
                                        <asp:TextBox ID="TextBox17" runat="server" Columns="40" 
                                            Text='<%# Bind("ExitReason") %>'></asp:TextBox>
                                    </InsertItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="Label17" runat="server" Text='<%# Bind("ExitReason") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Last (Monthly) Pay Received:" 
                                    SortExpression="LastPay">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="TextBox18" runat="server" 
                                            CssClass="defaultFormElementStyleRightAligned" Text='<%# Bind("LastPay") %>'></asp:TextBox>
                                    </EditItemTemplate>
                                    <InsertItemTemplate>
                                        N
                                        <asp:TextBox ID="TextBox19" runat="server" Columns="10" 
                                            CssClass="defaultFormElementStyleRightAligned" Text='<%# Bind("LastPay") %>'></asp:TextBox>
                                    </InsertItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="Label18" runat="server" Text='<%# Bind("LastPay") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Contact Person &amp; Telephone:" 
                                    SortExpression="Reference">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="TextBox20" runat="server" Text='<%# Bind("Reference") %>'></asp:TextBox>
                                    </EditItemTemplate>
                                    <InsertItemTemplate>
                                        <asp:TextBox ID="TextBox21" runat="server" Columns="40" 
                                            Text='<%# Bind("Reference") %>'></asp:TextBox>
                                    </InsertItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="Label19" runat="server" Text='<%# Bind("Reference") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Remark:" SortExpression="Remark">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="TextBox9" runat="server" Text='<%# Bind("Remark") %>'></asp:TextBox>
                                    </EditItemTemplate>
                                    <InsertItemTemplate>
                                        <asp:TextBox ID="TextBox22" runat="server" Columns="50" 
                                            CssClass="defaultFormElementStyle" Rows="5" Text='<%# Bind("Remark") %>' 
                                            TextMode="MultiLine"></asp:TextBox>
                                    </InsertItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="Label9" runat="server" Text='<%# Bind("Remark") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                            </Fields>
                            <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                            <AlternatingRowStyle BackColor="White" />
                        </asp:DetailsView>
                   </ItemTemplate>
                    <HeaderStyle HorizontalAlign="Left" VerticalAlign="Top" />
                    <ItemStyle HorizontalAlign="Left" VerticalAlign="Top" />
                </asp:TemplateField>
            </Columns>
            <EmptyDataRowStyle BorderColor="#CCCCCC" BorderStyle="Solid" BorderWidth="1px" 
                Font-Bold="True" />
            <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
            <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="Navy" />
            <RowStyle HorizontalAlign="Left" VerticalAlign="Top" BackColor="#FFFBD6" 
                ForeColor="#333333" />
            <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" 
                HorizontalAlign="Left" />
            <EditRowStyle CssClass="defaultFormElementStyle" />
            <AlternatingRowStyle BackColor="White" />
        </asp:GridView>
                    <asp:SqlDataSource ID="dsSqlGetDetail" runat="server" ConnectionString="<%$ ConnectionStrings:iTecon %>"
                        SelectCommand="SELECT [StaffEmploymentId], [StaffId], [EmployerName], [EmployerAddress], CAST(IsNull([StartDate], 0) AS DATETIME) AS StartDate, CAST(IsNull([EndDate], 0) AS DATETIME) AS EndDate, [ExitReason], IsNull([LastPay], 0) AS LastPay, [Reference], [Remark] FROM [dbo].[HR_Staff_PreviousEmployment] WHERE StaffId = @StaffId" 
                        DeleteCommand="STP_HR_DELETE_HR_Staff_PreviousEmployment" 
                        DeleteCommandType="StoredProcedure" 
                        InsertCommand="STP_HR_INSERT_HR_Staff_PreviousEmployment" 
                        InsertCommandType="StoredProcedure" 
                        UpdateCommand="STP_HR_UPDATE_HR_Staff_PreviousEmployment" 
                        UpdateCommandType="StoredProcedure">
                        <SelectParameters>
                            <asp:ControlParameter ControlID="gvMaster" Name="StaffId" 
                                PropertyName="SelectedValue" />
                        </SelectParameters>
                        <DeleteParameters>
                            <asp:Parameter Name="StaffEmploymentId" Type="Int32" />
                        </DeleteParameters>
                        <UpdateParameters>
                            <asp:Parameter Name="StaffEmploymentId" Type="Int32" />
                            <asp:Parameter Name="StaffId" Type="Int32" />
                            <asp:Parameter Name="EmployerName" Type="String" />
                            <asp:Parameter Name="EmployerAddress" Type="String" />
                            <asp:Parameter Name="StartDate" Type="DateTime" />
                            <asp:Parameter Name="EndDate" Type="DateTime" />
                            <asp:Parameter Name="ExitReason" Type="String" />
                            <asp:Parameter Name="LastPay" Type="Decimal" />
                            <asp:Parameter Name="Reference" Type="String" />
                            <asp:Parameter Name="Remark" Type="String" />
                        </UpdateParameters>
                        <InsertParameters>
                            <asp:Parameter Direction="InputOutput" Name="StaffEmploymentId" Type="Int32" />
                            <asp:Parameter Name="StaffId" Type="Int32" />
                            <asp:Parameter Name="EmployerName" Type="String" />
                            <asp:Parameter Name="EmployerAddress" Type="String" />
                            <asp:Parameter Name="StartDate" Type="DateTime" />
                            <asp:Parameter Name="EndDate" Type="DateTime" />
                            <asp:Parameter Name="ExitReason" Type="String" />
                            <asp:Parameter Name="LastPay" Type="Decimal" />
                            <asp:Parameter Name="Reference" Type="String" />
                            <asp:Parameter Name="Remark" Type="String" />
                        </InsertParameters>
                    </asp:SqlDataSource>
        <asp:SqlDataSource ID="dsoUsers" runat="server" ConnectionString="<%$ ConnectionStrings:iTecon %>"
                        SelectCommand="SELECT [StaffId], [StaffGUID], [StaffCode], [MaritalStatus], CAST(IsNull([WeddingDate], 0) AS DATETIME) AS WeddingDate, [Gender], [DateOfBirth], [ConfirmationStatus], [RetirementStatus], [Surname], [OtherNames], [Department], b.DepartmentName AS DepartmentName, CAST(IsNull([DateOfEmployment], 0) AS DATETIME) AS DateOfEmployment, [Email], a.[DesignationId], c.DesignationName, a.[JobLevelId], d.JobLevelName, a.[LocationId], e.LocationName, [Residence], [PermanentResidence], [Telephone], a.[ReligionId], f.ReligionName, [Hometown], a.[LGAOfOriginId], g.LgaName + ' LGA (' + h.StateName + ')' AS LgaName, a.[BankId], i.BankName, [BankAccountNumber], [Visa], [EyeColour], [Height], [Weight], [TrouserLength], [ShoeSize], [BloodGroup], [Genotype], [Hobbies], a.[AreaOfInterest], [VisaType], [Coop_MonthlyDeduction], [Coop_LoanRepayment], [MaxMedical], [NextOfKinName], [NextOfKinAddress], [NextOfKinRelationship] FROM [dbo].[HR_Staff_Base] a INNER JOIN dbo.[Core_Department] b ON a.Department = b.DepartmentCode LEFT JOIN dbo.[HR_Designation] c ON a.DesignationId = c.DesignationId LEFT JOIN dbo.[HR_JobLevel] d ON a.JobLevelId = d.JobLevelId LEFT JOIN dbo.[HR_Location] e ON a.LocationId = e.LocationId LEFT JOIN dbo.[HR_Religion] f ON a.ReligionId = f.ReligionId LEFT JOIN dbo.[Core_Lga] g ON a.LgaOfOriginId = g.LgaId LEFT JOIN dbo.[Core_State] h ON g.StateId = h.StateId LEFT JOIN dbo.[HR_Bank] i ON a.BankId = i.BankId ORDER BY Surname, OtherNames">
        </asp:SqlDataSource>
        <asp:ObjectDataSource ID="dsObjYears" runat="server" 
            SelectMethod="GetYearSeries" TypeName="Common">
        </asp:ObjectDataSource>
                </td>
            </tr>
            <tr>
                <td colspan="2">&nbsp;
                    </td>
            </tr>
        </table>
    
    </div>
    </form>
</body>
</html>
