<%@ Page Language="VB" AutoEventWireup="false" CodeFile="input_quals.aspx.vb" Inherits="modules_system_setups_metadata_managequals" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head id="Head1" runat="server">
    <title>Untitled Page</title>
    <link href="../../StyleSheet.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <form id="form1" runat="server">
    <div>
        <table border="0" width="100%">
            <tr>
                <td colspan="2">
                    <asp:Label ID="lblChooser" runat="server" Font-Bold="True" Font-Size="Small" 
                        Text=":: Please select a staff"></asp:Label></td>
            </tr>
            <tr>
                <td width="3%">&nbsp;
                    </td>
                <td>
                    <asp:DropDownList ID="DropDownList4" runat="server" 
                        CssClass="defaultFormElementStyle" DataSourceID="dsSqlGetAllStaff" 
                        DataTextField="StaffDetails" DataValueField="StaffId" AutoPostBack="True">
                    </asp:DropDownList>
                    <asp:SqlDataSource ID="dsSqlGetAllStaff" runat="server" 
                        ConnectionString="<%$ ConnectionStrings:iTecon %>" 
                        SelectCommand="SELECT 0 AS StaffId, ' Please select a staff ' AS StaffDetails UNION ALL SELECT [StaffId], UPPER([Surname]) + ' ' + UPPER([OtherNames]) + ' | ' + UPPER([StaffCode]) + ' | (' + UPPER([DepartmentName]) + ' Department)' FROM [HR_Staff_Base] a INNER JOIN [Core_Department] b ON a.Department = b.DepartmentId ">
                    </asp:SqlDataSource>
                </td>
            </tr>
            <tr>
              <td></td>
              <td><hr color="black" /></td>
            </tr>
            <tr>
                <td colspan="2">
                        <br />
						<asp:Label ID="lblHeader" runat="server" Font-Bold="True" Font-Size="Small" 
                        Text=":: Update Previous Academic Qualifications for the above Staff"></asp:Label></td>
            </tr>
            <tr>
                <td width="3%">&nbsp;
                    </td>
                <td>
                    <asp:GridView ID="gvUsers" runat="server" AllowSorting="True" AutoGenerateColumns="False"
                        AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True"
                        CssClass="noBorderedMenuTable" 
                        DataSourceID="dsSqlGetData" Width="1000px" CellPadding="4" ForeColor="#333333" 
                        GridLines="None" 
                        EmptyDataText="&amp;nbsp;&lt;br /&gt;No records to display.&lt;br /&gt;&amp;nbsp;" 
                        Visible="False" DataKeyNames="StaffCertificateId">
                        <Columns>
                            <asp:BoundField DataField="StaffCertificateId" HeaderText="Id" 
                                InsertVisible="False" ReadOnly="True" SortExpression="StaffCertificateId" />
                            <asp:TemplateField HeaderText="Staff Id" SortExpression="StaffId">
                                <EditItemTemplate>
                                    <asp:Label ID="Label8" runat="server" Text='<%# Bind("StaffId") %>'></asp:Label>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label6" runat="server" Text='<%# Bind("StaffId") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Certificate" SortExpression="CertificateCodeId">
                                <EditItemTemplate>
                                    <asp:DropDownList ID="ddlCertificate" runat="server" 
                                        CssClass="defaultFormElementStyle" DataSourceID="dsSqlGetCertificates2" 
                                        DataTextField="FullName" DataValueField="CertificateCodeId" 
                                        SelectedValue='<%# Bind("CertificateCodeId") %>'>
                                    </asp:DropDownList>
                                    <asp:SqlDataSource ID="dsSqlGetCertificates2" runat="server" 
                                        ConnectionString="<%$ ConnectionStrings:iTecon %>" 
                                        SelectCommand="SELECT [CertificateCodeId], [CertificateCodeName] + ' (' + [FullName] + ') ' AS FullName FROM [HR_CertificateCode] ORDER BY FullName">
                                    </asp:SqlDataSource>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label1" runat="server" Text='<%# Eval("FullName") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Discipline" SortExpression="DisciplineId">
                                <EditItemTemplate>
                                    <asp:DropDownList ID="DropDownList7" runat="server" 
                                        CssClass="defaultFormElementStyle" DataSourceID="dsSqlGetDisciplines" 
                                        DataTextField="DisciplineName" DataValueField="DisciplineId" 
                                        SelectedValue='<%# Bind("DisciplineId") %>'>
                                    </asp:DropDownList>
                                    <asp:SqlDataSource ID="dsSqlGetDisciplines" runat="server" 
                                        ConnectionString="<%$ ConnectionStrings:iTecon %>" 
                                        SelectCommand="SELECT [DisciplineId], [DisciplineName] FROM [HR_Discipline] ORDER BY [DisciplineName]">
                                    </asp:SqlDataSource>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label3" runat="server" Text='<%# Eval("DisciplineName") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Awarded By" 
                                SortExpression="CertificateTypeId">
                                <EditItemTemplate>
                                    <asp:DropDownList ID="DropDownList6" runat="server" 
                                        CssClass="defaultFormElementStyle" DataSourceID="dsSqlCertificateTypes2" 
                                        DataTextField="CertificateTypeName" DataValueField="CertificateTypeId" 
                                        SelectedValue='<%# Bind("CertificateTypeId") %>'>
                                    </asp:DropDownList>
                                    <asp:SqlDataSource ID="dsSqlCertificateTypes2" runat="server" 
                                        ConnectionString="<%$ ConnectionStrings:iTecon %>" 
                                        SelectCommand="SELECT [InstitutionId] AS CertificateTypeId, [InstitutionName] + ' (' + [CertificateTypeName] + ') ' AS CertificateTypeName FROM [HR_Institution] a INNER JOIN [HR_CertificateType] b ON a.InstitutionTypeId = b.CertificateTypeId ORDER BY CertificateTypeName">
                                    </asp:SqlDataSource>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label2" runat="server" Text='<%# Eval("CertificateTypeName") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Year Obtained" SortExpression="YearObtained">
                                <EditItemTemplate>
                                    <asp:DropDownList ID="ddlYearObtained_Edit" runat="server" 
                                        CssClass="defaultFormElementStyle" SelectedValue='<%# Bind("YearObtained") %>'>
                                        <asp:ListItem value="2011">2011</asp:ListItem>
                                        <asp:ListItem value="2010">2010</asp:ListItem>
                                        <asp:ListItem value="2009">2009</asp:ListItem>
                                        <asp:ListItem value="2008">2008</asp:ListItem>
                                        <asp:ListItem value="2007">2007</asp:ListItem>
                                        <asp:ListItem value="2006">2006</asp:ListItem>
                                        <asp:ListItem value="2005">2005</asp:ListItem>
                                        <asp:ListItem value="2004">2004</asp:ListItem>
                                        <asp:ListItem value="2003">2003</asp:ListItem>
                                        <asp:ListItem value="2002">2002</asp:ListItem>
                                        <asp:ListItem value="2001">2001</asp:ListItem>
                                        <asp:ListItem value="2000">2000</asp:ListItem>
                                        <asp:ListItem value="1999">1999</asp:ListItem>
                                        <asp:ListItem value="1998">1998</asp:ListItem>
                                        <asp:ListItem value="1997">1997</asp:ListItem>
                                        <asp:ListItem value="1996">1996</asp:ListItem>
                                        <asp:ListItem value="1995">1995</asp:ListItem>
                                        <asp:ListItem value="1994">1994</asp:ListItem>
                                        <asp:ListItem value="1993">1993</asp:ListItem>
                                        <asp:ListItem value="1992">1992</asp:ListItem>
                                        <asp:ListItem value="1991">1991</asp:ListItem>
                                        <asp:ListItem value="1990">1990</asp:ListItem>
                                        <asp:ListItem value="1989">1989</asp:ListItem>
                                        <asp:ListItem value="1988">1988</asp:ListItem>
                                        <asp:ListItem value="1987">1987</asp:ListItem>
                                        <asp:ListItem value="1986">1986</asp:ListItem>
                                        <asp:ListItem value="1985">1985</asp:ListItem>
                                        <asp:ListItem value="1984">1984</asp:ListItem>
                                        <asp:ListItem value="1983">1983</asp:ListItem>
                                        <asp:ListItem value="1982">1982</asp:ListItem>
                                        <asp:ListItem value="1981">1981</asp:ListItem>
                                        <asp:ListItem value="1980">1980</asp:ListItem>
                                        <asp:ListItem value="1979">1979</asp:ListItem>
                                        <asp:ListItem value="1978">1978</asp:ListItem>
                                        <asp:ListItem value="1977">1977</asp:ListItem>
                                        <asp:ListItem value="1976">1976</asp:ListItem>
                                        <asp:ListItem value="1975">1975</asp:ListItem>
                                        <asp:ListItem value="1974">1974</asp:ListItem>
                                        <asp:ListItem value="1973">1973</asp:ListItem>
                                        <asp:ListItem value="1972">1972</asp:ListItem>
                                        <asp:ListItem value="1971">1971</asp:ListItem>
                                        <asp:ListItem value="1970">1970</asp:ListItem>
                                        <asp:ListItem value="1969">1969</asp:ListItem>
                                        <asp:ListItem value="1968">1968</asp:ListItem>
                                        <asp:ListItem value="1967">1967</asp:ListItem>
                                        <asp:ListItem value="1966">1966</asp:ListItem>
                                        <asp:ListItem value="1965">1965</asp:ListItem>
                                        <asp:ListItem value="1964">1964</asp:ListItem>
                                        <asp:ListItem value="1963">1963</asp:ListItem>
                                        <asp:ListItem value="1962">1962</asp:ListItem>
                                        <asp:ListItem value="1961">1961</asp:ListItem>
                                    </asp:DropDownList>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label4" runat="server" Text='<%# Bind("YearObtained") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Entry Qual?" SortExpression="IsEntryQual">
                                <EditItemTemplate>
                                    <asp:DropDownList ID="DropDownList8" runat="server" 
                                        CssClass="defaultFormElementStyle" SelectedValue='<%# Bind("IsEntryQual") %>'>
                                        <asp:ListItem Value="N">No</asp:ListItem>
                                        <asp:ListItem Value="Y">Yes</asp:ListItem>
                                    </asp:DropDownList>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label5" runat="server" Text='<%# Common.GetYesOrNo(Databinder.Eval(Container.DataItem, "IsEntryQual").ToString) %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:BoundField DataField="Remark" HeaderText="Remark"
                                SortExpression="Remark" Visible="False" />
                        </Columns>
                        <RowStyle HorizontalAlign="Left" VerticalAlign="Top" BackColor="#FFFBD6" 
                            ForeColor="#333333" />
                        <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" 
                            HorizontalAlign="Left" VerticalAlign="Top" />
                        <EditRowStyle CssClass="defaultFormElementStyle" />
                        <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                        <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
                        <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="Navy" />
                        <AlternatingRowStyle BackColor="White" />
                    </asp:GridView>
                    <asp:SqlDataSource ID="dsSqlGetData" runat="server" ConnectionString="<%$ ConnectionStrings:iTecon %>"
                        SelectCommand="SELECT a.[StaffCertificateId], a.[StaffId], a.[CertificateCodeId], CertificateCodeName + ' (' + FullName + ')' AS FullName, c.InstitutionId AS CertificateTypeId, c.InstitutionName + ' (' + e.CertificateTypeName + ') ' AS CertificateTypeName, a.[DisciplineId], DisciplineName, YearObtained, IsEntryQual, a.[Remark] FROM [HR_Staff_Qualification] a INNER JOIN [HR_CertificateCode] b ON a.CertificateCodeId = b.CertificateCodeId INNER JOIN [HR_Institution] c ON a.CertificateTypeId = c.InstitutionId INNER JOIN [HR_Discipline] d ON a.DisciplineId = d.DisciplineId INNER JOIN [HR_CertificateType] e ON c.InstitutionTypeId = e.CertificateTypeId WHERE a.StaffId = @StaffId" 
                        DeleteCommand="STP_HR_DELETE_HR_Staff_Qualification" 
                        DeleteCommandType="StoredProcedure" 
                        InsertCommand="STP_HR_INSERT_HR_Staff_Qualification" 
                        InsertCommandType="StoredProcedure" 
                        UpdateCommand="STP_HR_UPDATE_HR_Staff_Qualification" 
                        UpdateCommandType="StoredProcedure">
                        <SelectParameters>
                            <asp:ControlParameter ControlID="DropDownList4" Name="StaffId" 
                                PropertyName="SelectedValue" />
                        </SelectParameters>
                        <DeleteParameters>
                            <asp:Parameter Name="StaffCertificateId" Type="Int32" />
                        </DeleteParameters>
                        <UpdateParameters>
                            <asp:Parameter Name="StaffCertificateId" Type="Int32" />
                            <asp:Parameter Name="StaffId" Type="Int32" />
                            <asp:Parameter Name="CertificateCodeId" Type="Int32" />
                            <asp:Parameter Name="CertificateTypeId" Type="Int32" />
                            <asp:Parameter Name="DisciplineId" Type="Int32" />
                            <asp:Parameter Name="YearObtained" Type="Int32" />
                            <asp:Parameter Name="IsEntryQual" Type="String" />
                            <asp:Parameter Name="Remark" Type="String" />
                        </UpdateParameters>
                        <InsertParameters>
                            <asp:Parameter Direction="InputOutput" Name="StaffCertificateId" Type="Int32" />
                            <asp:Parameter Name="StaffId" Type="Int32" />
                            <asp:Parameter Name="CertificateCodeId" Type="Int32" />
                            <asp:Parameter Name="CertificateTypeId" Type="Int32" />
                            <asp:Parameter Name="DisciplineId" Type="Int32" />
                            <asp:Parameter Name="YearObtained" Type="Int32" />
                            <asp:Parameter Name="IsEntryQual" Type="String" />
                            <asp:Parameter Name="Remark" Type="String" />
                        </InsertParameters>
                    </asp:SqlDataSource>
                </td>
            </tr>
            <tr>
                <td>
                </td>
                <td>
                    <hr color="black" />
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <br />
                    <asp:Label ID="lblAddNew" runat="server" Font-Bold="True" Font-Size="Small" 
                        Text=":: Add a New Academic Qualification for the above Staff"></asp:Label></td>
            </tr>
            <tr>
                <td>&nbsp;
                    </td>
                <td>
                    <asp:DetailsView ID="DetailsView1" runat="server" AutoGenerateRows="False"
                        DataSourceID="dsSqlGetData" DefaultMode="Insert" Width="800px" 
                        CellPadding="4" ForeColor="#333333" GridLines="None" 
                        AutoGenerateInsertButton="True" Visible="False">
                        <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                        <CommandRowStyle BackColor="#FFFFC0" Font-Bold="True" />
                        <RowStyle HorizontalAlign="Left" VerticalAlign="Top" Wrap="True" 
                            BackColor="#FFFBD6" ForeColor="#333333" />
                        <FieldHeaderStyle BackColor="#FFFF99" Font-Bold="True" Width="220px" />
                        <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
                        <Fields>
                            <asp:TemplateField HeaderText="Staff Concerned:" SortExpression="StaffId">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TextBox1" runat="server" Text='<%# Bind("StaffId") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <InsertItemTemplate>
                                    <asp:DropDownList ID="DropDownList5" runat="server" 
                                        CssClass="defaultFormElementStyle" DataSourceID="dsSqlGetSingleStaff" 
                                        DataTextField="StaffDetails" DataValueField="StaffId" 
                                        SelectedValue='<%# Bind("StaffId") %>'>
                                    </asp:DropDownList>
                                    <asp:SqlDataSource ID="dsSqlGetSingleStaff" runat="server" 
                                        ConnectionString="<%$ ConnectionStrings:iTecon %>" 
                                        SelectCommand="SELECT [StaffId], UPPER([Surname]) + ' ' + UPPER([OtherNames]) + ' | ' + UPPER([StaffCode]) + ' | (' + UPPER([DepartmentName]) + ' Department)' AS StaffDetails FROM [HR_Staff_Base] a INNER JOIN [Core_Department] b ON a.Department = b.DepartmentId WHERE StaffId = @StaffId">
                                        <SelectParameters>
                                            <asp:ControlParameter ControlID="DropDownList4" Name="StaffId" 
                                                PropertyName="SelectedValue" />
                                        </SelectParameters>
                                    </asp:SqlDataSource>
                                </InsertItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label1" runat="server" Text='<%# Bind("StaffId") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Certificate:" SortExpression="CertificateCodeId">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TextBox2" runat="server" 
                                        Text='<%# Bind("CertificateCodeId") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <InsertItemTemplate>
                                    <asp:DropDownList ID="DropDownList1" runat="server" 
                                        CssClass="defaultFormElementStyle" DataSourceID="dsSqlCertificateCodes" 
                                        DataTextField="FullName" DataValueField="CertificateCodeId" 
                                        SelectedValue='<%# Bind("CertificateCodeId") %>'>
                                    </asp:DropDownList>
                                    <asp:SqlDataSource ID="dsSqlCertificateCodes" runat="server" 
                                        ConnectionString="<%$ ConnectionStrings:iTecon %>" 
                                        SelectCommand="SELECT [CertificateCodeId], [CertificateCodeName] + ' (' + [FullName] + ')' AS FullName FROM [HR_CertificateCode]">
                                    </asp:SqlDataSource>
                                </InsertItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label2" runat="server" Text='<%# Bind("CertificateCodeId") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Discipline:" SortExpression="DisciplineId">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TextBox4" runat="server" Text='<%# Bind("DisciplineId") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <InsertItemTemplate>
                                    <asp:DropDownList ID="DropDownList3" runat="server" 
                                        CssClass="defaultFormElementStyle" DataSourceID="dsSqlDisciplines" 
                                        DataTextField="DisciplineName" DataValueField="DisciplineId" 
                                        SelectedValue='<%# Bind("DisciplineId") %>'>
                                    </asp:DropDownList>
                                    <asp:SqlDataSource ID="dsSqlDisciplines" runat="server" 
                                        ConnectionString="<%$ ConnectionStrings:iTecon %>" 
                                        SelectCommand="SELECT [DisciplineId], [DisciplineName] FROM [HR_Discipline]">
                                    </asp:SqlDataSource>
                                </InsertItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label4" runat="server" Text='<%# Bind("DisciplineId") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Awarding Institution:" 
                                SortExpression="CertificateTypeId">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TextBox3" runat="server" 
                                        Text='<%# Bind("CertificateTypeId") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <InsertItemTemplate>
                                    <asp:DropDownList ID="DropDownList2" runat="server" 
                                        CssClass="defaultFormElementStyle" DataSourceID="dsSqlCertificateTypes" 
                                        DataTextField="CertificateTypeName" DataValueField="CertificateTypeId" 
                                        SelectedValue='<%# Bind("CertificateTypeId") %>'>
                                    </asp:DropDownList>
                                    <asp:SqlDataSource ID="dsSqlCertificateTypes" runat="server" 
                                        ConnectionString="<%$ ConnectionStrings:iTecon %>" 
                                        SelectCommand="SELECT [InstitutionId] AS CertificateTypeId, [InstitutionName] + ' (' + [CertificateTypeName] + ') ' AS CertificateTypeName FROM [HR_Institution] a INNER JOIN [HR_CertificateType] b ON a.InstitutionTypeId = b.CertificateTypeId ORDER BY CertificateTypeName">
                                    </asp:SqlDataSource>
                                </InsertItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label3" runat="server" Text='<%# Bind("CertificateTypeId") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Year Obtained:" SortExpression="YearObtained">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TextBox6" runat="server" Text='<%# Bind("YearObtained") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <InsertItemTemplate>
                                    <asp:DropDownList ID="ddlYearObtained_New" runat="server" CssClass="defaultFormElementStyle" SelectedValue='<%# Bind("YearObtained") %>'>
				                        <asp:ListItem value="2011">2011</asp:ListItem>
				                        <asp:ListItem value="2010">2010</asp:ListItem>				                        
				                        <asp:ListItem value="2009">2009</asp:ListItem>				                        
				                        <asp:ListItem value="2008">2008</asp:ListItem>
				                        <asp:ListItem value="2007">2007</asp:ListItem>
				                        <asp:ListItem value="2006">2006</asp:ListItem>
				                        <asp:ListItem value="2005">2005</asp:ListItem>
				                        <asp:ListItem value="2004">2004</asp:ListItem>
				                        <asp:ListItem value="2003">2003</asp:ListItem>
				                        <asp:ListItem value="2002">2002</asp:ListItem>

				                        <asp:ListItem value="2001">2001</asp:ListItem>

				                        <asp:ListItem value="2000">2000</asp:ListItem>

				                        <asp:ListItem value="1999">1999</asp:ListItem>

				                        <asp:ListItem value="1998">1998</asp:ListItem>

				                        <asp:ListItem value="1997">1997</asp:ListItem>

				                        <asp:ListItem value="1996">1996</asp:ListItem>

				                        <asp:ListItem value="1995">1995</asp:ListItem>

				                        <asp:ListItem value="1994">1994</asp:ListItem>

				                        <asp:ListItem value="1993">1993</asp:ListItem>

				                        <asp:ListItem value="1992">1992</asp:ListItem>

				                        <asp:ListItem value="1991">1991</asp:ListItem>

				                        <asp:ListItem value="1990">1990</asp:ListItem>

				                        <asp:ListItem value="1989">1989</asp:ListItem>

				                        <asp:ListItem value="1988">1988</asp:ListItem>

				                        <asp:ListItem value="1987">1987</asp:ListItem>

				                        <asp:ListItem value="1986">1986</asp:ListItem>

				                        <asp:ListItem value="1985">1985</asp:ListItem>

				                        <asp:ListItem value="1984">1984</asp:ListItem>

				                        <asp:ListItem value="1983">1983</asp:ListItem>

				                        <asp:ListItem value="1982">1982</asp:ListItem>

				                        <asp:ListItem value="1981">1981</asp:ListItem>

				                        <asp:ListItem value="1980">1980</asp:ListItem>

				                        <asp:ListItem value="1979">1979</asp:ListItem>

				                        <asp:ListItem value="1978">1978</asp:ListItem>

				                        <asp:ListItem value="1977">1977</asp:ListItem>

				                        <asp:ListItem value="1976">1976</asp:ListItem>

				                        <asp:ListItem value="1975">1975</asp:ListItem>

				                        <asp:ListItem value="1974">1974</asp:ListItem>

				                        <asp:ListItem value="1973">1973</asp:ListItem>

				                        <asp:ListItem value="1972">1972</asp:ListItem>

				                        <asp:ListItem value="1971">1971</asp:ListItem>

				                        <asp:ListItem value="1970">1970</asp:ListItem>

				                        <asp:ListItem value="1969">1969</asp:ListItem>

				                        <asp:ListItem value="1968">1968</asp:ListItem>

				                        <asp:ListItem value="1967">1967</asp:ListItem>

				                        <asp:ListItem value="1966">1966</asp:ListItem>

				                        <asp:ListItem value="1965">1965</asp:ListItem>

				                        <asp:ListItem value="1964">1964</asp:ListItem>

				                        <asp:ListItem value="1963">1963</asp:ListItem>

				                        <asp:ListItem value="1962">1962</asp:ListItem>

				                        <asp:ListItem value="1961">1961</asp:ListItem>
                                    </asp:DropDownList>
                                </InsertItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label6" runat="server" Text='<%# Bind("YearObtained") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Is this an Entry Qualification?" 
                                SortExpression="IsEntryQual">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TextBox7" runat="server" Text='<%# Bind("IsEntryQual") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <InsertItemTemplate>
                                    <asp:DropDownList ID="DropDownList8" runat="server" 
                                        CssClass="defaultFormElementStyle" SelectedValue='<%# Bind("IsEntryQual") %>'>
                                        <asp:ListItem Value="N">No</asp:ListItem>
                                        <asp:ListItem Value="Y">Yes</asp:ListItem>
                                    </asp:DropDownList>
                                </InsertItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label7" runat="server" Text='<%# Bind("IsEntryQual") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Remark:" SortExpression="Remark">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TextBox5" runat="server" Text='<%# Bind("Remark") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <InsertItemTemplate>
                                    <asp:TextBox ID="TextBox5" runat="server" Columns="50" Rows="5" 
                                        Text='<%# Bind("Remark") %>' TextMode="MultiLine" 
                                        CssClass="defaultFormElementStyle"></asp:TextBox>
                                </InsertItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label5" runat="server" Text='<%# Bind("Remark") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                        </Fields>
                        <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                        <AlternatingRowStyle BackColor="White" />
                    </asp:DetailsView>
                    &nbsp; &nbsp;&nbsp;</td>
            </tr>
            <tr>
                <td colspan="2">&nbsp;
                    </td>
            </tr>
        </table>
    
    </div>
    </form>
</body>
</html>
