<%@ Page Language="VB" AutoEventWireup="false" CodeFile="input_training_2.aspx.vb" Inherits="modules_hr_input_training_2" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head id="Head1" runat="server">
    <title>Untitled Page</title>
    <link href="../../../StyleSheet.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <form id="form1" runat="server">
    <div>
        <table border="0" width="100%">
            <tr>
                <td colspan="2">
						<asp:Label ID="lblHeader" runat="server" Font-Bold="True" Font-Size="Small" 
                        Text=":: Edit Professional Trainings"></asp:Label></td>
            </tr>
            <tr>
                <td width="3%">&nbsp;
                    </td>
                <td>
        <asp:GridView ID="gvMaster" runat="server" CssClass="noBorderedMenuTable" AutoGenerateColumns="False" 
                    DataKeyNames="StaffId" DataSourceID="dsoUsers" AllowSorting="True" 
                    CellPadding="4" ForeColor="#333333" GridLines="None" Width="1000px" 
                        SelectedIndex="0" PageSize="50" 
                        
                        EmptyDataText="&lt;br /&gt;&lt;br /&gt;No staff records found&lt;br /&gt;&lt;br /&gt;&amp;nbsp;" >
            <Columns>
                <asp:TemplateField HeaderText="Staff Code" SortExpression="StaffCode">
                    <EditItemTemplate>
                        <asp:Label ID="TextBox47" runat="server" Text='<%# Bind("StaffCode") %>'></asp:Label>
                   </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label49" runat="server" Text='<%# Bind("StaffCode") %>'></asp:Label>
                    </ItemTemplate>
                    <ItemStyle Width="70px" />
                </asp:TemplateField>
                <asp:TemplateField>
                    <ItemTemplate>
                        <asp:Image ID="Image1" runat="server" Height="30px" 
                        ImageUrl='<%# "~\images\pp_staff\" & Databinder.Eval(Container.DataItem, "StaffCode").ToString & ".jpg" %>' 
                        Width="30px" BorderColor="Black" BorderStyle="Solid" BorderWidth="2px" /><br /><asp:Label ID="Label49_2" runat="server" Text='<%# Databinder.Eval(Container.DataItem, "Surname").ToString.ToUpper & " " & Databinder.Eval(Container.DataItem, "OtherNames").ToString.ToUpper %>'></asp:Label>
                    </ItemTemplate>
                    <ItemStyle Width="60px" />
                </asp:TemplateField>
                <asp:CommandField SelectText="Show Professional Trainings" 
                    ShowSelectButton="True">
                <ItemStyle Width="80px" />
                </asp:CommandField>
                <asp:TemplateField HeaderText="PROFESSIONAL TRAININGS">
                    <ItemTemplate>
                        <asp:GridView ID="gvDetail" runat="server" AutoGenerateColumns="False" 
                            AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
                            AutoGenerateSelectButton="True" CellPadding="4" CssClass="noBorderedMenuTable" 
                            DataKeyNames="StaffTrainingId" DataSourceID="dsSqlGetDetail" 
                            EmptyDataText="&amp;nbsp;&lt;br /&gt;No records to display.&lt;br /&gt;&amp;nbsp;" 
                            ForeColor="#333333" GridLines="None" Visible="False" Width="100%" 
                            AllowSorting="True" Font-Bold="false" >
                            <Columns>
                                <asp:BoundField DataField="StaffTrainingId" HeaderText="Id" 
                                    InsertVisible="False" ReadOnly="True" SortExpression="StaffTrainingId" />
                                <asp:TemplateField HeaderText="Staff Id" SortExpression="StaffId">
                                    <EditItemTemplate>
                                        <asp:Label ID="Label4" runat="server" Text='<%# Bind("StaffId") %>'></asp:Label>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="Label2" runat="server" Text='<%# Bind("StaffId") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Training Programme" 
                                    SortExpression="TrainingId">
                                    <EditItemTemplate>
                                        <asp:DropDownList ID="DropDownList9" runat="server" 
                                            CssClass="defaultFormElementStyle" 
                                            SelectedValue='<%# Bind("TrainingId") %>' DataSourceID="dsSqlTrainings1" 
                                            DataTextField="TrainingDesc" DataValueField="TrainingId">
                                        </asp:DropDownList>
                                        <asp:SqlDataSource ID="dsSqlTrainings1" runat="server" 
                                            ConnectionString="<%$ ConnectionStrings:iTecon %>" 
                                            SelectCommand="SELECT a.[TrainingId], a.CourseName + ' (' + CAST(a.DurationInDays AS VARCHAR) + ' days; ' + b.ProviderName + '; ' + b.ProviderAddress + ')' AS TrainingDesc FROM [dbo].[HR_Training] a INNER JOIN dbo.[HR_TrainingProvider] b ON a.TrainingProviderId = b.TrainingProviderId">
                                        </asp:SqlDataSource>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="Label1" runat="server" 
                                            Text='<%# Bind("TrainingDesc") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:BoundField DataField="Remark" HeaderText="Remark" SortExpression="Remark" 
                                    Visible="False" />
                            </Columns>
                            <RowStyle BackColor="#FFFBD6" ForeColor="#333333" HorizontalAlign="Left" 
                                VerticalAlign="Top" />
                            <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" 
                                HorizontalAlign="Left" VerticalAlign="Top" />
                            <EditRowStyle CssClass="defaultFormElementStyle" />
                            <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                            <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
                            <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="Navy" />
                            <AlternatingRowStyle BackColor="White" />
                        </asp:GridView>
                   <br />
                        <asp:Label ID="lblAddNew" runat="server" Font-Bold="True" Font-Size="Small" 
                        Text=":: Add a New Professional Training" CssClass="defaultHeaderTextStyle" 
                            Visible="False"></asp:Label>
                        <asp:DetailsView ID="DetailsView1" runat="server" 
                            AutoGenerateInsertButton="True" AutoGenerateRows="False" CellPadding="4" 
                            DataKeyNames="StaffTrainingId" DataSourceID="dsSqlGetDetail" 
                            DefaultMode="Insert" ForeColor="#333333" GridLines="None" Visible="False" 
                            Width="100%" Font-Bold="false" OnItemInserted="DetailsViewItemInserted">
                            <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                            <CommandRowStyle BackColor="#FFFFC0" Font-Bold="True" />
                            <RowStyle BackColor="#FFFBD6" ForeColor="#333333" HorizontalAlign="Left" 
                                VerticalAlign="Top" Wrap="True" />
                            <FieldHeaderStyle BackColor="#FFFF99" Font-Bold="True" Width="220px" />
                            <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
                            <Fields>
                                <asp:BoundField DataField="StaffTrainingId" HeaderText="StaffTrainingId" 
                                    InsertVisible="False" ReadOnly="True" SortExpression="StaffTrainingId" />
                                <asp:TemplateField HeaderText="Staff Concerned:" SortExpression="StaffId">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="TextBox2" runat="server" Text='<%# Bind("StaffId") %>'></asp:TextBox>
                                    </EditItemTemplate>
                                    <InsertItemTemplate>
                                        <asp:DropDownList ID="DropDownList5" runat="server" 
                                            CssClass="defaultFormElementStyle" DataSourceID="dsSqlGetSingleStaff" 
                                            DataTextField="StaffDetails" DataValueField="StaffId" 
                                            SelectedValue='<%# Bind("StaffId") %>'>
                                        </asp:DropDownList>
                                        <asp:SqlDataSource ID="dsSqlGetSingleStaff" runat="server" 
                                            ConnectionString="<%$ ConnectionStrings:iTecon %>" 
                                            SelectCommand="SELECT [StaffId], UPPER([Surname]) + ' ' + UPPER([OtherNames]) + ' | ' + UPPER([StaffCode]) + ' | (' + UPPER(b.[DepartmentName]) + ' Department)' AS StaffDetails FROM [HR_Staff_Base] a INNER JOIN [Core_Department] b ON a.Department = b.DepartmentCode WHERE StaffId = @StaffId">
                                            <SelectParameters>
                                                <asp:ControlParameter ControlID="gvMaster" Name="StaffId" 
                                                    PropertyName="SelectedValue" />
                                            </SelectParameters>
                                        </asp:SqlDataSource>
                                    </InsertItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="Label5" runat="server" Text='<%# Bind("StaffId") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Training Programme:" SortExpression="TrainingId">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="TextBox1" runat="server" Text='<%# Bind("TrainingId") %>'></asp:TextBox>
                                    </EditItemTemplate>
                                    <InsertItemTemplate>
                                        <asp:DropDownList ID="DropDownList5_2" runat="server" 
                                            CssClass="defaultFormElementStyle" DataSourceID="dsSqlTrainings2" 
                                            DataTextField="TrainingDesc" DataValueField="TrainingId" 
                                            SelectedValue='<%# Bind("TrainingId") %>'>
                                        </asp:DropDownList>
                                        <asp:SqlDataSource ID="dsSqlTrainings2" runat="server" 
                                            ConnectionString="<%$ ConnectionStrings:iTecon %>" 
                                            SelectCommand="SELECT a.[TrainingId], a.CourseName + ' (' + CAST(a.DurationInDays AS VARCHAR) + ' days; ' + b.ProviderName + '; ' + b.ProviderAddress + ')' AS TrainingDesc FROM [dbo].[HR_Training] a INNER JOIN dbo.[HR_TrainingProvider] b ON a.TrainingProviderId = b.TrainingProviderId">
                                        </asp:SqlDataSource>
                                    </InsertItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="Label6" runat="server" Text='<%# Bind("TrainingId") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Remark:" SortExpression="Remark">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="TextBox3" runat="server" Text='<%# Bind("Remark") %>'></asp:TextBox>
                                    </EditItemTemplate>
                                    <InsertItemTemplate>
                                        <asp:TextBox ID="TextBox4" runat="server" Columns="50" 
                                            CssClass="defaultFormElementStyle" Rows="5" Text='<%# Bind("Remark") %>' 
                                            TextMode="MultiLine"></asp:TextBox>
                                    </InsertItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="Label3" runat="server" Text='<%# Bind("Remark") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                            </Fields>
                            <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                            <AlternatingRowStyle BackColor="White" />
                        </asp:DetailsView>
                   </ItemTemplate>
                    <HeaderStyle HorizontalAlign="Left" VerticalAlign="Top" />
                    <ItemStyle HorizontalAlign="Left" VerticalAlign="Top" />
                </asp:TemplateField>
            </Columns>
            <EmptyDataRowStyle BorderColor="#CCCCCC" BorderStyle="Solid" BorderWidth="1px" 
                Font-Bold="True" />
            <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
            <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="Navy" />
            <RowStyle HorizontalAlign="Left" VerticalAlign="Top" BackColor="#FFFBD6" 
                ForeColor="#333333" />
            <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" 
                HorizontalAlign="Left" />
            <EditRowStyle CssClass="defaultFormElementStyle" />
            <AlternatingRowStyle BackColor="White" />
        </asp:GridView>
                    <asp:SqlDataSource ID="dsSqlGetDetail" runat="server" ConnectionString="<%$ ConnectionStrings:iTecon %>"
                        SelectCommand="SELECT [StaffTrainingId], [StaffId], a.[TrainingId], b.CourseName + ' (' + CAST(b.DurationInDays AS VARCHAR) + ' days; ' + c.ProviderName + '; ' + c.ProviderAddress + ')' AS TrainingDesc, a.[Remark] FROM [dbo].[HR_Staff_Training] a INNER JOIN dbo.[HR_Training] b ON a.TrainingId = b.TrainingId INNER JOIN dbo.[HR_TrainingProvider] c ON b.TrainingProviderId = c.TrainingProviderId WHERE StaffId = @StaffId" 
                        DeleteCommand="STP_HR_DELETE_HR_Staff_Training" 
                        DeleteCommandType="StoredProcedure" 
                        InsertCommand="STP_HR_INSERT_HR_Staff_Training" 
                        InsertCommandType="StoredProcedure" 
                        UpdateCommand="STP_HR_UPDATE_HR_Staff_Training" 
                        UpdateCommandType="StoredProcedure">
                        <SelectParameters>
                            <asp:ControlParameter ControlID="gvMaster" Name="StaffId" 
                                PropertyName="SelectedValue" />
                        </SelectParameters>
                        <DeleteParameters>
                            <asp:Parameter Name="StaffTrainingId" Type="Int32" />
                        </DeleteParameters>
                        <UpdateParameters>
                            <asp:Parameter Name="StaffTrainingId" Type="Int32" />
                            <asp:Parameter Name="StaffId" Type="Int32" />
                            <asp:Parameter Name="TrainingId" Type="Int32" />
                            <asp:Parameter Name="Remark" Type="String" />
                        </UpdateParameters>
                        <InsertParameters>
                            <asp:Parameter Direction="InputOutput" Name="StaffTrainingId" Type="Int32" />
                            <asp:Parameter Name="StaffId" Type="Int32" />
                            <asp:Parameter Name="TrainingId" Type="Int32" />
                            <asp:Parameter Name="Remark" Type="String" />
                        </InsertParameters>
                    </asp:SqlDataSource>
        <asp:SqlDataSource ID="dsoUsers" runat="server" ConnectionString="<%$ ConnectionStrings:iTecon %>"
                        SelectCommand="SELECT [StaffId], [StaffGUID], [StaffCode], [MaritalStatus], CAST(IsNull([WeddingDate], 0) AS DATETIME) AS WeddingDate, [Gender], [DateOfBirth], [ConfirmationStatus], [RetirementStatus], [Surname], [OtherNames], [Department], b.DepartmentName AS DepartmentName, CAST(IsNull([DateOfEmployment], 0) AS DATETIME) AS DateOfEmployment, [Email], a.[DesignationId], c.DesignationName, a.[JobLevelId], d.JobLevelName, a.[LocationId], e.LocationName, [Residence], [PermanentResidence], [Telephone], a.[ReligionId], f.ReligionName, [Hometown], a.[LGAOfOriginId], g.LgaName + ' LGA (' + h.StateName + ')' AS LgaName, a.[BankId], i.BankName, [BankAccountNumber], [Visa], [EyeColour], [Height], [Weight], [TrouserLength], [ShoeSize], [BloodGroup], [Genotype], [Hobbies], a.[AreaOfInterest], [VisaType], [Coop_MonthlyDeduction], [Coop_LoanRepayment], [MaxMedical], [NextOfKinName], [NextOfKinAddress], [NextOfKinRelationship] FROM [dbo].[HR_Staff_Base] a INNER JOIN dbo.[Core_Department] b ON a.Department = b.DepartmentCode LEFT JOIN dbo.[HR_Designation] c ON a.DesignationId = c.DesignationId LEFT JOIN dbo.[HR_JobLevel] d ON a.JobLevelId = d.JobLevelId LEFT JOIN dbo.[HR_Location] e ON a.LocationId = e.LocationId LEFT JOIN dbo.[HR_Religion] f ON a.ReligionId = f.ReligionId LEFT JOIN dbo.[Core_Lga] g ON a.LgaOfOriginId = g.LgaId LEFT JOIN dbo.[Core_State] h ON g.StateId = h.StateId LEFT JOIN dbo.[HR_Bank] i ON a.BankId = i.BankId ORDER BY Surname, OtherNames">
        </asp:SqlDataSource>
                </td>
            </tr>
            <tr>
                <td colspan="2">&nbsp;
                    </td>
            </tr>
        </table>
    
    </div>
    </form>
</body>
</html>
