<%@ Page Language="VB" AutoEventWireup="false" CodeFile="managestates.aspx.vb" Inherits="modules_system_setups_metadata_managestates" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head runat="server">
    <title>Untitled Page</title>
    <link href="../../../../StyleSheet.css" rel="stylesheet" type="text/css" />
</head>
<body topmargin="0" leftmargin="0">
    <form id="form1" runat="server">
    <div>
    
    <table border="0" width="100%">
            <tr>
                <td colspan="2">
                    <br />
                                <asp:Label ID="Label4" runat="server" Font-Bold="True" Font-Size="Small" Text=":: Add a New State"></asp:Label></td>
            </tr>
            <tr>
                <td>
                    &nbsp;</td>
                <td>
                    <asp:DetailsView ID="DetailsView1" runat="server" AutoGenerateRows="False" CssClass="noBorderedMenuTable"
                        DataKeyNames="StateId,CountryId1" DataSourceID="dsSqlStates" DefaultMode="Insert"
                        Height="50px" CellPadding="4" ForeColor="#333333" GridLines="None" 
                        Width="600px" EnableModelValidation="True">
                        <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                        <EditRowStyle Wrap="True" />
                        <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                        <CommandRowStyle BackColor="#FFFFC0" Font-Bold="True" />
                        <RowStyle HorizontalAlign="Left" VerticalAlign="Top" Wrap="True" 
                            BackColor="#FFFBD6" ForeColor="#333333" />
                        <FieldHeaderStyle BackColor="#FFFF99" Font-Bold="True" />
                        <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
                        <Fields>
                            <asp:BoundField DataField="StateId" HeaderText="StateId" InsertVisible="False" ReadOnly="True"
                                SortExpression="StateId" />
                            <asp:BoundField DataField="StateName" HeaderText="State:" 
                                SortExpression="StateName" />
                            <asp:TemplateField HeaderText="Country:" SortExpression="CountryName">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TextBox1" runat="server" Text='<%# Bind("CountryName") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <InsertItemTemplate>
                                    <asp:DropDownList ID="DropDownList2" runat="server" CssClass="defaultFormElementStyle"
                                        DataSourceID="dsSqlCountries" DataTextField="CountryName" DataValueField="CountryId"
                                        SelectedValue='<%# Bind("CountryId") %>'>
                                    </asp:DropDownList><asp:SqlDataSource ID="dsSqlCountries" runat="server" ConnectionString="<%$ ConnectionStrings:iTecon %>"
                                        SelectCommand="SELECT [CountryId], [CountryName] FROM [Core_Country] ORDER BY [CountryName]">
                                    </asp:SqlDataSource>
                                </InsertItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label1" runat="server" Text='<%# Bind("CountryName") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:CommandField ShowInsertButton="True" ButtonType="Button" 
                                InsertText="Add New State" />
                        </Fields>
                        <AlternatingRowStyle BackColor="White" />
                    </asp:DetailsView>
                    &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</td>
            </tr>
            <tr>
                <td>
                </td>
                <td>
                    <hr color="black" />
                </td>
            </tr>
            <tr>
                <td colspan="2">
                                <asp:Label ID="Label5" runat="server" Font-Bold="True" Font-Size="Small" Text=":: Edit Existing States"></asp:Label></td>
            </tr>
            <tr>
                <td width="3%">
                    &nbsp;</td>
                <td>
                                <asp:GridView ID="gvUsers" runat="server" AllowSorting="True" AutoGenerateColumns="False"
                        AutoGenerateEditButton="True" AutoGenerateSelectButton="True" CssClass="noBorderedMenuTable"
                        DataKeyNames="StateId" DataSourceID="dsSqlStates" AutoGenerateDeleteButton="True" 
                                    AllowPaging="True" PageSize="50" CellPadding="4" ForeColor="#333333" 
                                    GridLines="None" Width="800px">
                        <Columns>
                            <asp:TemplateField HeaderText="StateId" InsertVisible="False" SortExpression="StateId">
                                <EditItemTemplate>
                                    <asp:Label ID="Label12" runat="server" Text='<%# Eval("StateId") %>'></asp:Label>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label13" runat="server" Text='<%# Bind("StateId") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="State" SortExpression="StateName">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TextBox7" runat="server" Text='<%# Bind("StateName") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label2" runat="server" Text='<%# Bind("StateName") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Country" SortExpression="CountryName">
                                <EditItemTemplate>
                                    <asp:DropDownList ID="DropDownList1" runat="server" 
                                        CssClass="defaultFormElementStyle" DataSourceID="dsSqlCountries0" 
                                        DataTextField="CountryName" DataValueField="CountryId" 
                                        SelectedValue='<%# Bind("CountryId") %>'>
                                    </asp:DropDownList><asp:SqlDataSource ID="dsSqlCountries0" runat="server" ConnectionString="<%$ ConnectionStrings:iTecon %>"
                                        
                                        SelectCommand="SELECT DISTINCT [CountryId], [CountryName] FROM [Core_Country] ORDER BY [CountryName]">
                                    </asp:SqlDataSource>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label3" runat="server" Text='<%# Bind("CountryName") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                        </Columns>
                        <RowStyle HorizontalAlign="Left" VerticalAlign="Top" BackColor="#FFFBD6" 
                                        ForeColor="#333333" />
                                    <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" 
                                        HorizontalAlign="Left" />
                        <EditRowStyle CssClass="defaultFormElementStyle" />
                                    <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                                    <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
                        <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="Navy" />
                                    <AlternatingRowStyle BackColor="White" />
                    </asp:GridView>
                    <asp:SqlDataSource ID="dsSqlStates" runat="server" ConnectionString="<%$ ConnectionStrings:iTecon %>"
                        DeleteCommand="STP_METADATA_DELETE_STATE" DeleteCommandType="StoredProcedure"
                        InsertCommand="STP_METADATA_INSERT_STATE" InsertCommandType="StoredProcedure"
                        SelectCommand="STP_METADATA_SELECT_STATE_ALL" SelectCommandType="StoredProcedure"
                        UpdateCommand="STP_METADATA_UPDATE_STATE" UpdateCommandType="StoredProcedure">
                        <DeleteParameters>
                            <asp:Parameter Name="StateId" Type="Int32" />
                        </DeleteParameters>
                        <UpdateParameters>
                            <asp:Parameter Name="StateId" Type="Int32" />
                            <asp:Parameter Name="StateName" Type="String" />
                            <asp:Parameter Name="CountryId" Type="Int32" />
                        </UpdateParameters>
                        <InsertParameters>
                            <asp:Parameter Name="StateName" Type="String" />
                            <asp:Parameter Name="CountryId" Type="Int32" />
                        </InsertParameters>
                    </asp:SqlDataSource>
                    &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    &nbsp;</td>
            </tr>
        </table>
        
    
    </div>


    </form>


</body>
</html>
