<%@ Page Language="VB" AutoEventWireup="false" CodeFile="default.aspx.vb" Inherits="modules_system_users_default" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head runat="server">
    <title>Untitled Page</title>
    <link href="../../../../StyleSheet.css" rel="stylesheet" type="text/css" />
    <script src="../../../../inc_functions_js_CalendarPopup_Combined.js" type="text/javascript"></script>
<script language="javascript" type="text/javascript">
// <!CDATA[

function TABLE1_onclick() {

}

// ]]>
</script>
</head>
<body topmargin="0" leftmargin="0">
    <form id="form1" runat="server">
    <div>
        <table width="100%"  border="0" id="TABLE1" onclick="return TABLE1_onclick()">
            <tr>
                <td colspan="2">
                    <br />
        <asp:Label ID="Label17" runat="server" Font-Bold="True" Font-Size="Small" 
                        Text=":: Create a New User"></asp:Label></td>
            </tr>
            <tr>
            <td>&nbsp;</td>
            <td>
        <asp:DetailsView ID="DetailsView1" runat="server" AutoGenerateRows="False"
            DataKeyNames="UserId" DataSourceID="dsoUsers" Height="50px" 
                    CssClass="noBorderedMenuTable" DefaultMode="Insert" CellPadding="4" 
                    ForeColor="#333333" GridLines="None" Width="600px" 
                    EnableModelValidation="True">
            <FieldHeaderStyle BackColor="#FFFF99" Font-Bold="True" />
            <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
            <Fields>
                <asp:TemplateField HeaderText="User Id:" SortExpression="UserId">
                    <EditItemTemplate>
                        <asp:Label ID="Label19" runat="server" Text='<%# Eval("UserId") %>'></asp:Label>
                    </EditItemTemplate>
                    <InsertItemTemplate>
                        <asp:Label ID="Label20" runat="server" 
                            Text='<%# "<-- to be auto-generated by the database -->" %>'></asp:Label>
                    </InsertItemTemplate>
                    <ItemStyle Wrap="False" />
                    <ItemTemplate>
                        <asp:Label ID="Label21" runat="server" Text='<%# Bind("UserId") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="User Code:" SortExpression="UserCode">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox9" runat="server" Text='<%# Bind("UserCode") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <InsertItemTemplate>
                        <asp:Label ID="Label18" runat="server" Text='<%# "<-- to be auto-generated by the database -->" %>'></asp:Label>
                    </InsertItemTemplate>
                    <ItemStyle Wrap="False" />
                    <ItemTemplate>
                        <asp:Label ID="Label22" runat="server" Text='<%# Bind("UserCode") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:BoundField DataField="Username" HeaderText="Username:" 
                    SortExpression="Username">
                    <ItemStyle Wrap="False" />
                </asp:BoundField>
                <asp:TemplateField HeaderText="Date Of Birth:" SortExpression="DateOfBirth">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox10" runat="server" Text='<%# Bind("DateOfBirth") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <InsertItemTemplate>
                        <script language="JavaScript" id="jsClientSideCalendar">
                            var clientSideCalendarAdd = new CalendarPopup("divCalendarAdd");
                            clientSideCalendarAdd.showNavigationDropdowns();
                        </script>
                        <DIV ID="divCalendarAdd" STYLE="position:absolute;visibility:hidden;background-color:white;layer-background-color:white;"></DIV>
                        <asp:TextBox ID="txtCalendarAdd" runat="server" Columns="25" 
                            CssClass="defaultFormElementStyle" Text='<%# Bind("DateOfBirth") %>'></asp:TextBox>
                        <a href="#" onclick="clientSideCalendarAdd.select(document.forms[0].DetailsView1_txtCalendarAdd,'anchorCalendarAdd','MM/dd/yyyy'); return false;" title="clientSideCalendarAdd.select(document.forms[0].DetailsView1_txtCalendarAdd,'anchorCalendarAdd','MM/dd/yyyy'); return false;" name="anchorCalendarAdd" id="anchorCalendarAdd">select</a>
                        &nbsp;
                    </InsertItemTemplate>
                    <ItemStyle Wrap="False" />
                    <ItemTemplate>
                        <asp:Label ID="Label23" runat="server" Text='<%# Bind("DateOfBirth") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:BoundField DataField="Email" HeaderText="Email:" SortExpression="Email">
                    <ItemStyle Wrap="False" />
                </asp:BoundField>
                <asp:BoundField DataField="Telephone" HeaderText="Telephone:" 
                    SortExpression="Telephone">
                    <ItemStyle Wrap="False" />
                </asp:BoundField>
                <asp:TemplateField HeaderText="Marital Status:" SortExpression="MaritalStatus">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox11" runat="server" Text='<%# Bind("MaritalStatus") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <InsertItemTemplate>
                        <asp:DropDownList ID="DropDownList9" runat="server" 
                            SelectedValue='<%# Bind("MaritalStatus") %>' CssClass="defaultFormElementStyle">
                            <asp:ListItem Value="0">Single</asp:ListItem>
                            <asp:ListItem Value="1">Married</asp:ListItem>
                            <asp:ListItem Value="2">Divorced</asp:ListItem>
                            <asp:ListItem Value="3">Widowed</asp:ListItem>
                        </asp:DropDownList>
                    </InsertItemTemplate>
                    <ItemStyle Wrap="False" />
                    <ItemTemplate>
                        <asp:Label ID="Label24" runat="server" Text='<%# Bind("MaritalStatus") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Title:" SortExpression="Firstname">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox2" runat="server" Text='<%# Bind("Firstname") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <InsertItemTemplate>
                        <asp:DropDownList ID="ddlAddTitle" runat="server" 
                            CssClass="defaultFormElementStyle" SelectedValue='<%# Bind("Firstname") %>'>
                            <asp:ListItem>Miss</asp:ListItem>
                            <asp:ListItem>Mr.</asp:ListItem>
                            <asp:ListItem>Mrs.</asp:ListItem>
                        </asp:DropDownList>
                    </InsertItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label1" runat="server" Text='<%# Bind("Firstname") %>'></asp:Label>
                    </ItemTemplate>
                    <ItemStyle Wrap="False" />
                </asp:TemplateField>
                <asp:BoundField DataField="Middlename" HeaderText="First Name:" 
                    SortExpression="Middlename">
                    <ItemStyle Wrap="False" />
                </asp:BoundField>
                <asp:BoundField DataField="Surname" HeaderText="Surname:" 
                    SortExpression="Surname">
                    <ItemStyle Wrap="False" />
                </asp:BoundField>
                <asp:BoundField DataField="Password" HeaderText="Password:" 
                    SortExpression="Password">
                    <ItemStyle Wrap="False" />
                </asp:BoundField>
                <asp:BoundField DataField="ResidenceStreet" HeaderText="Street Address:" 
                    SortExpression="ResidenceStreet">
                    <ItemStyle Wrap="False" />
                </asp:BoundField>
                <asp:TemplateField HeaderText="State Of Residence:" 
                    SortExpression="ResidenceStateId">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox12" runat="server" 
                            Text='<%# Bind("ResidenceStateId") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <InsertItemTemplate>
                        <asp:DropDownList ID="DropDownList6" runat="server" CssClass="defaultFormElementStyle"
                            DataSourceID="dsSqlStates0" DataTextField="StateName" DataValueField="StateId"
                            SelectedValue='<%# Bind("ResidenceStateId") %>'>
                        </asp:DropDownList><asp:SqlDataSource ID="dsSqlStates0" runat="server" ConnectionString="<%$ ConnectionStrings:iTecon %>"
                            SelectCommand="STP_METADATA_SELECT_STATE_ALL" 
                            SelectCommandType="StoredProcedure">
                        </asp:SqlDataSource>
                    </InsertItemTemplate>
                    <ItemStyle Wrap="False" />
                    <ItemTemplate>
                        <asp:Label ID="Label25" runat="server" Text='<%# Bind("ResidenceStateId") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Country Of Residence:" 
                    SortExpression="ResidenceCountryId">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox13" runat="server" 
                            Text='<%# Bind("ResidenceCountryId") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <InsertItemTemplate>
                        <asp:DropDownList ID="DropDownList7" runat="server" CssClass="defaultFormElementStyle"
                            DataSourceID="dsSqlCountries0" DataTextField="CountryName" DataValueField="CountryId"
                            SelectedValue='<%# Bind("ResidenceCountryId") %>'>
                        </asp:DropDownList><asp:SqlDataSource ID="dsSqlCountries0" runat="server" ConnectionString="<%$ ConnectionStrings:iTecon %>"
                            SelectCommand="STP_METADATA_SELECT_COUNTRY_ALL" 
                            SelectCommandType="StoredProcedure">
                        </asp:SqlDataSource>
                    </InsertItemTemplate>
                    <ItemStyle Wrap="False" />
                    <ItemTemplate>
                        <asp:Label ID="Label26" runat="server" Text='<%# Bind("ResidenceCountryId") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Gender:" SortExpression="Sex">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox14" runat="server" Text='<%# Bind("Sex") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <InsertItemTemplate>
                        <asp:DropDownList ID="DropDownList10" runat="server" 
                            SelectedValue='<%# Bind("Sex") %>' CssClass="defaultFormElementStyle">
                            <asp:ListItem Value="F">Female</asp:ListItem>
                            <asp:ListItem Value="M">Male</asp:ListItem>
                        </asp:DropDownList>
                    </InsertItemTemplate>
                    <ItemStyle Wrap="False" />
                    <ItemTemplate>
                        <asp:Label ID="Label27" runat="server" Text='<%# Bind("Sex") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Department:" SortExpression="DepartmentId">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox15" runat="server" Text='<%# Bind("DepartmentId") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <InsertItemTemplate>
                        <asp:DropDownList ID="DropDownList8" runat="server" CssClass="defaultFormElementStyle"
                            DataSourceID="dsSqlDepartments0" DataTextField="DepartmentName" DataValueField="DepartmentId"
                            SelectedValue='<%# Bind("DepartmentId") %>'>
                        </asp:DropDownList><asp:SqlDataSource ID="dsSqlDepartments0" runat="server" ConnectionString="<%$ ConnectionStrings:iTecon %>"
                            SelectCommand="STP_METADATA_SELECT_DEPARTMENT_ALL" 
                            SelectCommandType="StoredProcedure">
                        </asp:SqlDataSource>
                    </InsertItemTemplate>
                    <ItemStyle Wrap="False" />
                    <ItemTemplate>
                        <asp:Label ID="Label28" runat="server" Text='<%# Bind("DepartmentId") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:CommandField ShowInsertButton="True" ButtonType="Button" 
                    InsertText="Add New User" />
            </Fields>
            <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
            <EditRowStyle Wrap="True" />
            <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
            <CommandRowStyle BackColor="#FFFFC0" Font-Bold="True" />
            <RowStyle Wrap="True" HorizontalAlign="Left" VerticalAlign="Top" 
                BackColor="#FFFBD6" ForeColor="#333333" />
            <AlternatingRowStyle BackColor="White" />
        </asp:DetailsView>
                &nbsp; &nbsp;</td>
            </tr>
            <tr>
                <td>
                </td>
                <td>
        <hr color="black" />
                </td>
            </tr>
          <tr>
            <td colspan="2"><asp:Label ID="lblHeader" runat="server" Text=":: Edit Existing Users" Font-Bold="True" Font-Size="Small"></asp:Label></td>
          </tr>
          <tr>
            <td width="3%">&nbsp;</td>
            <td>
        <asp:GridView ID="gvUsers" runat="server" CssClass="noBorderedMenuTable" 
                    AutoGenerateColumns="False" AutoGenerateDeleteButton="True" 
                    AutoGenerateEditButton="True" AutoGenerateSelectButton="True" PageSize="30" 
                    DataKeyNames="UserId" DataSourceID="dsoUsers" AllowSorting="True" 
                    CellPadding="4" ForeColor="#333333" GridLines="None" 
                    EnableModelValidation="True" Width="2000px" >
            <Columns>
                <asp:TemplateField HeaderText="User Id" SortExpression="UserId">
                    <EditItemTemplate>
                        <asp:Label ID="Label1" runat="server" Text='<%# Eval("UserId") %>'></asp:Label>
                    </EditItemTemplate>
                    <ItemStyle Wrap="False" />
                    <ItemTemplate>
                        <asp:Label ID="Label1" runat="server" Text='<%# Bind("UserId") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="User Code" SortExpression="UserCode">
                    <EditItemTemplate>
                        <asp:Label ID="Label4" runat="server" Text='<%# Bind("UserCode") %>'></asp:Label>
                    </EditItemTemplate>
                    <ItemStyle Wrap="False" />
                    <ItemTemplate>
                        <asp:Label ID="Label3" runat="server" Text='<%# Bind("UserCode") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Username" SortExpression="Username">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox1" runat="server" CssClass="defaultFormElementStyle" Text='<%# Bind("Username") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemStyle Wrap="False" />
                    <ItemTemplate>
                        <asp:Label ID="Label9" runat="server" Text='<%# Bind("Username") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Date of Birth" SortExpression="DateOfBirth">
                    <EditItemTemplate>
                        <script language="JavaScript" id="jsClientSideCalendar">
                            var clientSideCalendarEdit = new CalendarPopup("divCalendarEdit");
                            clientSideCalendarEdit.showNavigationDropdowns();
                        </script>
                        <DIV ID="divCalendarEdit" STYLE="position:absolute;visibility:hidden;background-color:white;layer-background-color:white;"></DIV>
                        <asp:TextBox ID="txtCalendarEdit" runat="server" Columns="25" 
                            CssClass="defaultFormElementStyle" Text='<%# Bind("DateOfBirth") %>'></asp:TextBox>
                        <a href="#" onclick="clientSideCalendarEdit.select(document.forms[0].gvUsers_ctl02_txtCalendarEdit,'anchorCalendarEdit','MM/dd/yyyy'); return false;" title="clientSideCalendarEdit.select(document.forms[0].gvUsers_ctl02_txtCalendarEdit,'anchorCalendarEdit','MM/dd/yyyy'); return false;" name="anchorCalendarEdit" id="anchorCalendarEdit">select</a>
                        &nbsp;
                    </EditItemTemplate>
                    <ItemStyle Wrap="False" />
                    <ItemTemplate>
                        <asp:Label ID="Label8" runat="server" Text='<%# Eval("DateOfBirth") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Email" SortExpression="Email">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox2" runat="server" CssClass="defaultFormElementStyle" Text='<%# Bind("Email") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemStyle Wrap="False" />
                    <ItemTemplate>
                        <asp:Label ID="Label10" runat="server" Text='<%# Bind("Email") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Telephone" SortExpression="Telephone">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox3" runat="server" CssClass="defaultFormElementStyle" Text='<%# Bind("Telephone") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemStyle Wrap="False" />
                    <ItemTemplate>
                        <asp:Label ID="Label11" runat="server" Text='<%# Bind("Telephone") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Marital Status" SortExpression="MaritalStatus">
                    <EditItemTemplate>
                        <asp:DropDownList ID="DropDownList1" runat="server" SelectedValue='<%# Bind("MaritalStatus") %>' CssClass="defaultFormElementStyle">
                            <asp:ListItem Value="0">Single</asp:ListItem>
                            <asp:ListItem Value="1">Married</asp:ListItem>
                            <asp:ListItem Value="2">Divorced</asp:ListItem>
                            <asp:ListItem Value="3">Widowed</asp:ListItem>
                        </asp:DropDownList>
                    </EditItemTemplate>
                    <ItemStyle Wrap="False" />
                    <ItemTemplate>
                        <asp:Label ID="Label2" runat="server" Text='<%# Eval("MaritalStatus") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Title" SortExpression="Firstname">
                    <EditItemTemplate>
                        <asp:DropDownList ID="ddlAddTitle" runat="server" 
                            CssClass="defaultFormElementStyle" SelectedValue='<%# Bind("Firstname") %>'>
                            <asp:ListItem>Miss</asp:ListItem>
                            <asp:ListItem>Mr.</asp:ListItem>
                            <asp:ListItem>Mrs.</asp:ListItem>
                        </asp:DropDownList>
                    </EditItemTemplate>
                    <ItemStyle Wrap="False" />
                    <ItemTemplate>
                        <asp:Label ID="Label12" runat="server" Text='<%# Bind("Firstname") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="First Name" SortExpression="Middlename">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox5" runat="server" CssClass="defaultFormElementStyle" Text='<%# Bind("Middlename") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemStyle Wrap="False" />
                    <ItemTemplate>
                        <asp:Label ID="Label13" runat="server" Text='<%# Bind("Middlename") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Surname" SortExpression="Surname">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox6" runat="server" CssClass="defaultFormElementStyle" Text='<%# Bind("Surname") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemStyle Wrap="False" />
                    <ItemTemplate>
                        <asp:Label ID="Label14" runat="server" Text='<%# Bind("Surname") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Password" SortExpression="Password">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox7" runat="server" CssClass="defaultFormElementStyle" Text='<%# Bind("Password") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemStyle Wrap="False" />
                    <ItemTemplate>
                        <asp:Label ID="Label15" runat="server" Text='<%# Bind("Password") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Street Address" SortExpression="ResidenceStreet">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox8" runat="server" CssClass="defaultFormElementStyle" Text='<%# Bind("ResidenceStreet") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemStyle Wrap="False" />
                    <ItemTemplate>
                        <asp:Label ID="Label16" runat="server" Text='<%# Bind("ResidenceStreet") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="State of Residence" 
                    SortExpression="ResidenceStateId">
                    <EditItemTemplate>
                        <asp:DropDownList ID="DropDownList2" runat="server" DataSourceID="dsSqlStates" DataTextField="StateName"
                            DataValueField="StateId" SelectedValue='<%# Bind("ResidenceStateId") %>' CssClass="defaultFormElementStyle">
                        </asp:DropDownList><asp:SqlDataSource ID="dsSqlStates" runat="server" ConnectionString="<%$ ConnectionStrings:iTecon %>"
                            SelectCommand="SELECT [StateId], [StateName] FROM [Core_State]"></asp:SqlDataSource>
                    </EditItemTemplate>
                    <ItemStyle Wrap="False" />
                    <ItemTemplate>
                        <asp:Label ID="Label4" runat="server" Text='<%# Bind("StateName") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Country of Residence" 
                    SortExpression="ResidenceCountryId">
                    <EditItemTemplate>
                        <asp:DropDownList ID="DropDownList3" runat="server" DataSourceID="dsSqlCountries"
                            DataTextField="CountryName" DataValueField="CountryId" SelectedValue='<%# Bind("ResidenceCountryId") %>' CssClass="defaultFormElementStyle">
                        </asp:DropDownList><asp:SqlDataSource ID="dsSqlCountries" runat="server" ConnectionString="<%$ ConnectionStrings:iTecon %>"
                            SelectCommand="SELECT [CountryId], [CountryName] FROM [Core_Country]"></asp:SqlDataSource>
                    </EditItemTemplate>
                    <ItemStyle Wrap="False" />
                    <ItemTemplate>
                        <asp:Label ID="Label5" runat="server" Text='<%# Bind("CountryName") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Gender" SortExpression="Sex">
                    <EditItemTemplate>
                        <asp:DropDownList ID="DropDownList4" runat="server" SelectedValue='<%# Bind("Sex") %>' CssClass="defaultFormElementStyle">
                            <asp:ListItem Value="F">Female</asp:ListItem>
                            <asp:ListItem Value="M">Male</asp:ListItem>
                        </asp:DropDownList>
                    </EditItemTemplate>
                    <ItemStyle Wrap="False" />
                    <ItemTemplate>
                        <asp:Label ID="Label6" runat="server" Text='<%# Bind("Sex") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Department" SortExpression="DepartmentId">
                    <EditItemTemplate>
                        <asp:DropDownList ID="DropDownList5" runat="server" DataSourceID="dsSqlDepartments"
                            DataTextField="DepartmentName" DataValueField="DepartmentId" SelectedValue='<%# Bind("DepartmentId") %>' CssClass="defaultFormElementStyle">
                        </asp:DropDownList><asp:SqlDataSource ID="dsSqlDepartments" runat="server" ConnectionString="<%$ ConnectionStrings:iTecon %>"
                            SelectCommand="STP_METADATA_SELECT_DEPARTMENT_ALL" SelectCommandType="StoredProcedure">
                        </asp:SqlDataSource>
                    </EditItemTemplate>
                    <ItemStyle Wrap="False" />
                    <ItemTemplate>
                        <asp:Label ID="Label7" runat="server" Text='<%# Bind("DepartmentName") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
            </Columns>
            <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
            <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="Navy" />
            <RowStyle HorizontalAlign="Left" VerticalAlign="Top" BackColor="#FFFBD6" 
                ForeColor="#333333" />
            <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" 
                HorizontalAlign="Left" />
            <EditRowStyle CssClass="defaultFormElementStyle" />
            <AlternatingRowStyle BackColor="White" />
        </asp:GridView>
        <asp:SqlDataSource ID="dsoUsers" runat="server" ConnectionString="<%$ ConnectionStrings:iTecon %>"
            DeleteCommand="STP_METADATA_DELETE_USER" DeleteCommandType="StoredProcedure"
            InsertCommand="STP_METADATA_INSERT_USER" InsertCommandType="StoredProcedure"
            SelectCommand="STP_METADATA_SELECT_USER_ALL" SelectCommandType="StoredProcedure"
            UpdateCommand="STP_METADATA_UPDATE_USER" UpdateCommandType="StoredProcedure">
            <DeleteParameters>
                <asp:Parameter Name="UserId" Type="Int32" />
                <asp:Parameter Name="UserCode" Type="String" />
            </DeleteParameters>
            <UpdateParameters>
                <asp:Parameter Name="UserId" Type="Int32" />
                <asp:Parameter Name="UserCode" Type="String" />
                <asp:Parameter Name="Username" Type="String" />
                <asp:Parameter Name="DateOfBirth" Type="DateTime" />
                <asp:Parameter Name="Email" Type="String" />
                <asp:Parameter Name="Telephone" Type="String" />
                <asp:Parameter Name="MaritalStatus" Type="String" />
                <asp:Parameter Name="Firstname" Type="String" />
                <asp:Parameter Name="Middlename" Type="String" />
                <asp:Parameter Name="Surname" Type="String" />
                <asp:Parameter Name="Password" Type="String" />
                <asp:Parameter Name="ResidenceStreet" Type="String" />
                <asp:Parameter Name="ResidenceStateId" Type="Int32" />
                <asp:Parameter Name="ResidenceCountryId" Type="Int32" />
                <asp:Parameter Name="Sex" Type="String" />
                <asp:Parameter Name="DepartmentId" Type="Int32" />
            </UpdateParameters>
            <InsertParameters>
                <asp:Parameter Name="Username" Type="String" />
                <asp:Parameter Name="DateOfBirth" Type="DateTime" />
                <asp:Parameter Name="Email" Type="String" />
                <asp:Parameter Name="Telephone" Type="String" />
                <asp:Parameter Name="MaritalStatus" Type="String" />
                <asp:Parameter Name="Firstname" Type="String" />
                <asp:Parameter Name="Middlename" Type="String" />
                <asp:Parameter Name="Surname" Type="String" />
                <asp:Parameter Name="Password" Type="String" />
                <asp:Parameter Name="ResidenceStreet" Type="String" />
                <asp:Parameter Name="ResidenceStateId" Type="Int32" />
                <asp:Parameter Name="ResidenceCountryId" Type="Int32" />
                <asp:Parameter Name="Sex" Type="String" />
                <asp:Parameter Name="DepartmentId" Type="Int32" />
            </InsertParameters>
        </asp:SqlDataSource>
        &nbsp;</td>
          </tr>
          <tr>
            <td colspan="2">&nbsp;</td>
          </tr>
      </table>
      </div>
    </form>
</body>
</html>
