<%@ Page Language="VB" AutoEventWireup="false" CodeFile="managesyllabus_2.aspx.vb" Inherits="modules_academics_managesyllabus_2" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head id="Head1" runat="server">
    <title>Untitled Page</title>
    <link href="../../StyleSheet.css" rel="stylesheet" type="text/css" />
</head>
<body topmargin="20" leftmargin="20">
    <form id="form1" runat="server">
    <div>
        <table border="0" width="100%">
            <tr>
                <td colspan="2">
                    <asp:Label ID="lblHeader" runat="server" Font-Bold="True" Font-Size="Small" 
                        Text=""></asp:Label></td>
            </tr>
            <tr>
                <td width="3%">
                    &nbsp;</td>
                <td>
        <asp:GridView ID="gvMaster" runat="server" CssClass="noBorderedMenuTable" AutoGenerateColumns="False" 
                    DataKeyNames="SubjectId,ClassName" DataSourceID="dsSqlSubjects" AllowSorting="True" 
                    CellPadding="4" ForeColor="#333333" GridLines="None" Width="100%" 
                        SelectedIndex="0" EmptyDataText="No record(s) to display." 
                        EnableModelValidation="True" >
            <Columns>
                <asp:TemplateField HeaderText="SN" SortExpression="">
                    <ItemTemplate>
                        <asp:Label ID="lblSerial" runat="server" Text='<%# serial  %>'></asp:Label>
                    </ItemTemplate>
                    <ItemStyle Width="20px" />
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Class &amp; Subject">
                    <ItemTemplate>
                        <asp:Label ID="lblClassName" runat="server" Text='<%# Bind("ClassName") %>'></asp:Label>&nbsp;<br />(<asp:Label 
                            ID="lblSubjectShortName" runat="server" Text='<%# Bind("SubjectName") %>'></asp:Label>)
                    </ItemTemplate>
                    <ItemStyle Width="250px" />
                </asp:TemplateField>
                <asp:CommandField SelectText="Add/Edit Lesson Notes" ShowSelectButton="True">
                <ItemStyle Width="150px" />
                </asp:CommandField>
                <asp:TemplateField HeaderText="Lesson Notes for this Class &amp; Subject">
                    <ItemTemplate>
                        <asp:GridView ID="gvDetail" runat="server" AutoGenerateColumns="False" 
                            AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
                            AutoGenerateSelectButton="True" CellPadding="4" CssClass="noBorderedMenuTable" 
                            DataKeyNames="LessonNoteId" DataSourceID="dsSqlSyllabus" 
                            ForeColor="#333333" GridLines="None" Width="100%" AllowSorting="True" 
                            EnableModelValidation="True" Visible="False" 
                            EmptyDataText="No record(s) available." 
                            OnRowDataBound="gvDetail_RowDataBound">
                            <Columns>
                                <asp:BoundField DataField="LessonNoteId" HeaderText="Id" InsertVisible="False" 
                                    ReadOnly="True" SortExpression="LessonNoteId" />
                                <asp:TemplateField HeaderText="Subject" SortExpression="SubjectShortName">
                                    <ItemTemplate>
                                        <asp:Label ID="Label6" runat="server" Text='<%# Bind("SubjectShortName") %>'></asp:Label>
                                    </ItemTemplate>
                                    <EditItemTemplate>
                                        <asp:Label ID="Label9" runat="server" Text='<%# Bind("SubjectShortName") %>'></asp:Label>
                                    </EditItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Class" SortExpression="ClassName">
                                    <ItemTemplate>
                                        <asp:Label ID="Label7" runat="server" Text='<%# Bind("ClassName") %>'></asp:Label>
                                    </ItemTemplate>
                                    <EditItemTemplate>
                                        <asp:Label ID="Label10" runat="server" Text='<%# Bind("ClassName") %>'></asp:Label>
                                    </EditItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Week #" SortExpression="WeekNumber">
                                    <ItemTemplate>
                                        <asp:Label ID="Label8" runat="server" Text='<%# Bind("WeekNumber") %>'></asp:Label>
                                    </ItemTemplate>
                                    <EditItemTemplate>
                                        <asp:DropDownList ID="ddlWeekNumberEdit" runat="server" 
                                            CssClass="defaultFormElementStyle" DataSourceID="dsObjSerialNumbers" 
                                            SelectedValue='<%# Bind("WeekNumber") %>'>
                                        </asp:DropDownList>
                                    </EditItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Lesson #" SortExpression="LessonNumber">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="TextBox3b" runat="server" Columns="5" 
                                            Text='<%# Bind("LessonNumber") %>'></asp:TextBox>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="Label12" runat="server" Text='<%# Bind("LessonNumber") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Topic" SortExpression="LessonTopic">
                                    <ItemTemplate>
                                        <asp:Label ID="Label13" runat="server" Text='<%# Bind("LessonTopic") %>'></asp:Label>
                                    </ItemTemplate>
                                    <EditItemTemplate>
                                        <asp:TextBox ID="TextBox9" runat="server" Columns="20" 
                                            CssClass="defaultFormElementStyle" Rows="3" Text='<%# Bind("LessonTopic") %>' 
                                            TextMode="MultiLine"></asp:TextBox>
                                    </EditItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Objectives" 
                                    SortExpression="LessonObjectives">
                                    <ItemTemplate>
                                        <asp:Label ID="Label3" runat="server" Text='<%# Bind("LessonObjectives") %>'></asp:Label>
                                    </ItemTemplate>
                                    <EditItemTemplate>
                                        <asp:TextBox ID="TextBox3" runat="server" 
                                            Text='<%# Bind("LessonObjectives") %>' Columns="20" 
                                            CssClass="defaultFormElementStyle" Rows="7" TextMode="MultiLine"></asp:TextBox>
                                    </EditItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Method" SortExpression="LessonMethod">
                                    <ItemTemplate>
                                        <asp:Label ID="Label1" runat="server" Text='<%# Bind("LessonMethod") %>'></asp:Label>
                                    </ItemTemplate>
                                    <EditItemTemplate>
                                        <asp:TextBox ID="TextBox1" runat="server" Text='<%# Bind("LessonMethod") %>' 
                                            Columns="20" CssClass="defaultFormElementStyle" Rows="7" TextMode="MultiLine"></asp:TextBox>
                                    </EditItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Homework" SortExpression="LessonHomework">
                                    <ItemTemplate>
                                        <asp:Label ID="Label2" runat="server" Text='<%# Bind("LessonHomework") %>'></asp:Label>
                                    </ItemTemplate>
                                    <EditItemTemplate>
                                        <asp:TextBox ID="TextBox2" runat="server" Text='<%# Bind("LessonHomework") %>' 
                                            Columns="20" CssClass="defaultFormElementStyle" Rows="7" TextMode="MultiLine"></asp:TextBox>
                                    </EditItemTemplate>
                                </asp:TemplateField>
                            </Columns>
                            <RowStyle BackColor="#FFFBD6" ForeColor="#333333" HorizontalAlign="Left" 
                                VerticalAlign="Top" />
                            <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" 
                                HorizontalAlign="Left" />
                            <EditRowStyle CssClass="defaultFormElementStyle" />
                            <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                            <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
                            <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="Navy" />
                            <AlternatingRowStyle BackColor="White" />
                        </asp:GridView>
                        <br />
                        <asp:Label ID="lblAddNew" runat="server" Font-Bold="True" Font-Size="Small" 
                            Text=":: Add a New Lesson Note" Visible="False"></asp:Label>
                        <br />
                        <asp:DetailsView ID="dvSubjectSyllabus" runat="server" CellPadding="4" 
                            ForeColor="#333333" GridLines="None" Height="50px" Width="600px" 
                            AutoGenerateRows="False" DataKeyNames="LessonNoteId" 
                            DataSourceID="dsSqlSyllabus" DefaultMode="Insert" 
                            EnableModelValidation="True" Visible="False" 
                            OnItemInserted="DetailsViewItemInserted">
                            <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                            <CommandRowStyle BackColor="#FFFFC0" Font-Bold="True" />
                            <RowStyle BackColor="#FFFBD6" ForeColor="#333333" HorizontalAlign="Left" VerticalAlign="Top" Wrap="True" />
                            <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
                            <Fields>
                                <asp:BoundField DataField="LessonNoteId" HeaderText="LessonNoteId" 
                                    InsertVisible="False" ReadOnly="True" SortExpression="LessonNoteId" />
                                <asp:TemplateField HeaderText="Subject:" SortExpression="SubjectShortName">
                                    <ItemTemplate>
                                        <asp:Label ID="Label1" runat="server" Text='<%# Bind("SubjectShortName") %>'></asp:Label>
                                    </ItemTemplate>
                                    <InsertItemTemplate>
                                        <asp:DropDownList ID="ddlSubjectAdd" runat="server" 
                                            CssClass="defaultFormElementStyle" DataSourceID="dsSqlSubjectsAdd_Edit" 
                                            DataTextField="SubjectName" DataValueField="ShortName" 
                                            SelectedValue='<%# Bind("SubjectShortName") %>'>
                                        </asp:DropDownList>
                                    </InsertItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Class:" SortExpression="ClassName">
                                    <ItemTemplate>
                                        <asp:Label ID="Label2" runat="server" Text='<%# Bind("ClassName") %>'></asp:Label>
                                    </ItemTemplate>
                                    <InsertItemTemplate>
                                        <asp:DropDownList ID="ddlClassAdd" runat="server" 
                                            CssClass="defaultFormElementStyle" DataSourceID="dsSqlClassesAdd_Edit" 
                                            DataTextField="ClassName" DataValueField="ClassName" 
                                            SelectedValue='<%# Bind("ClassName") %>'>
                                        </asp:DropDownList>
                                    </InsertItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Week #:" SortExpression="WeekNumber">
                                    <ItemTemplate>
                                        <asp:Label ID="Label3" runat="server" Text='<%# Bind("WeekNumber") %>'></asp:Label>
                                    </ItemTemplate>
                                    <InsertItemTemplate>
                                        <asp:DropDownList ID="ddlWeekNumberAdd" runat="server" 
                                            CssClass="defaultFormElementStyle" DataSourceID="dsObjSerialNumbers" 
                                            SelectedValue='<%# Bind("WeekNumber") %>'>
                                        </asp:DropDownList>
                                    </InsertItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Lesson #:" SortExpression="LessonNumber">
                                    <ItemTemplate>
                                        <asp:Label ID="Label4" runat="server" Text='<%# Bind("LessonNumber") %>'></asp:Label>
                                    </ItemTemplate>
                                    <InsertItemTemplate>
                                        <asp:TextBox ID="TextBox4" runat="server" Text='<%# Bind("LessonNumber") %>' 
                                            Columns="10"></asp:TextBox>
                                    </InsertItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Topic:" SortExpression="LessonTopic">
                                    <ItemTemplate>
                                        <asp:Label ID="Label5" runat="server" Text='<%# Bind("LessonTopic") %>'></asp:Label>
                                    </ItemTemplate>
                                    <InsertItemTemplate>
                                        <asp:TextBox ID="TextBox5" runat="server" Text='<%# Bind("LessonTopic") %>' 
                                            Columns="60" CssClass="defaultFormElementStyle" Rows="3"></asp:TextBox>
                                    </InsertItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Objectives:" 
                                    SortExpression="LessonObjectives">
                                    <ItemTemplate>
                                        <asp:Label ID="Label6" runat="server" Text='<%# Bind("LessonObjectives") %>'></asp:Label>
                                    </ItemTemplate>
                                    <InsertItemTemplate>
                                        <asp:TextBox ID="TextBox6" runat="server" 
                                            Text='<%# Bind("LessonObjectives") %>' Columns="60" 
                                            CssClass="defaultFormElementStyle" Rows="7" TextMode="MultiLine"></asp:TextBox>
                                    </InsertItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Method of Teaching:" 
                                    SortExpression="LessonMethod">
                                    <ItemTemplate>
                                        <asp:Label ID="Label7" runat="server" Text='<%# Bind("LessonMethod") %>'></asp:Label>
                                    </ItemTemplate>
                                    <InsertItemTemplate>
                                        <asp:TextBox ID="TextBox7" runat="server" Text='<%# Bind("LessonMethod") %>' 
                                            Columns="60" CssClass="defaultFormElementStyle" Rows="5" TextMode="MultiLine"></asp:TextBox>
                                    </InsertItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Homework:" 
                                    SortExpression="LessonHomework">
                                    <ItemTemplate>
                                        <asp:Label ID="Label8" runat="server" Text='<%# Bind("LessonHomework") %>'></asp:Label>
                                    </ItemTemplate>
                                    <InsertItemTemplate>
                                        <asp:TextBox ID="TextBox8" runat="server" Text='<%# Bind("LessonHomework") %>' 
                                            Columns="60" CssClass="defaultFormElementStyle" Rows="7" TextMode="MultiLine"></asp:TextBox>
                                    </InsertItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Term:" SortExpression="TermName">
                                    <ItemTemplate>
                                        <asp:Label ID="Label9" runat="server" Text='<%# Bind("TermName") %>'></asp:Label>
                                    </ItemTemplate>
                                    <InsertItemTemplate>
                                        <asp:DropDownList ID="DropDownList1" runat="server" 
                                            CssClass="defaultFormElementStyle" DataSourceID="dsSqlTermsAdd" 
                                            DataTextField="TermName" DataValueField="TermName" 
                                            SelectedValue='<%# Bind("Remark") %>'>
                                        </asp:DropDownList>
                                        <asp:SqlDataSource ID="dsSqlTermsAdd" runat="server" 
                                            ConnectionString="<%$ ConnectionStrings:iTecon %>" 
                                            SelectCommand="SELECT '2nd Term' as TermName"></asp:SqlDataSource>
                                    </InsertItemTemplate>
                                </asp:TemplateField>
                                <asp:CommandField ShowInsertButton="True" />
                            </Fields>
                            <FieldHeaderStyle BackColor="#FFFF99" Font-Bold="True" />
                            <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                            <AlternatingRowStyle BackColor="White" />
                        </asp:DetailsView>
                        <br />
                   </ItemTemplate>
                    <HeaderStyle HorizontalAlign="Left" VerticalAlign="Top" />
                    <ItemStyle HorizontalAlign="Left" VerticalAlign="Top" />
                </asp:TemplateField>
            </Columns>
            <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
            <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="Navy" />
            <RowStyle HorizontalAlign="Left" VerticalAlign="Top" BackColor="#FFFBD6" 
                ForeColor="#333333" />
            <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" 
                HorizontalAlign="Left" />
            <EditRowStyle CssClass="defaultFormElementStyle" />
            <AlternatingRowStyle BackColor="White" />
        </asp:GridView>
                    <asp:SqlDataSource ID="dsSqlSyllabus" runat="server" ConnectionString="<%$ ConnectionStrings:iTecon %>"
                        DeleteCommand="STP_LESSONNOTE_DELETE_TEMPLessonNote" DeleteCommandType="StoredProcedure"
                        InsertCommand="STP_LESSONNOTE_INSERT_TEMPLessonNote" InsertCommandType="StoredProcedure"
                        SelectCommand=" SELECT LessonNoteId, a.[SubjectShortName], b.SubjectName, b.ShortName, ClassName, ClassName + SubjectShortName as ClassSubject, WeekNumber, LessonNumber, LessonTopic, LessonObjectives, LessonMethod, LessonHomework, Remark as TermName, Remark2 as SessionName FROM [dbo].[TEMPLessonNote] a INNER JOIN dbo.TEMPSubject b ON a.SubjectShortName = b.ShortName WHERE ClassName = @ClassName AND SubjectShortName = (SELECT ShortName FROM dbo.TEMPSubject WHERE SubjectId = @SubjectId) AND a.Remark = @TermName AND a.Remark2 = @SessionName ORDER BY WeekNumber, LessonNumber "
                        UpdateCommand="STP_LESSONNOTE_UPDATE_TEMPLessonNote" 
                        UpdateCommandType="StoredProcedure">
                        <SelectParameters>
                            <asp:ControlParameter Name="ClassName" ControlID="gvMaster" PropertyName="SelectedDataKey(1)" />
                            <asp:ControlParameter Name="SubjectId" ControlID="gvMaster" PropertyName="SelectedValue" />
                            <asp:Parameter Name="TermName" />
                            <asp:Parameter Name="SessionName" />
                        </SelectParameters>
                        <DeleteParameters>
                            <asp:Parameter Name="LessonNoteId" Type="Int32" />
                        </DeleteParameters>
                        <UpdateParameters>
                            <asp:Parameter Name="LessonNoteId" Type="Int32" />
                            <asp:Parameter Name="SubjectShortName" Type="String" />
                            <asp:Parameter Name="ClassName" Type="String" />
                            <asp:Parameter Name="WeekNumber" Type="Int32" />
                            <asp:Parameter Name="LessonNumber" Type="String" />
                            <asp:Parameter Name="LessonTopic" Type="String" />
                            <asp:Parameter Name="LessonObjectives" Type="String" />
                            <asp:Parameter Name="LessonMethod" Type="String" />
                            <asp:Parameter Name="LessonHomework" Type="String" />
                            <asp:Parameter Name="Remark" Type="String" />
                            <asp:Parameter Name="Remark2" Type="String" />
                            <asp:Parameter Name="Remark3" Type="String" />
                        </UpdateParameters>
                        <InsertParameters>
                            <asp:Parameter Name="LessonNoteId" Type="Int32" Direction="InputOutput" />
                            <asp:Parameter Name="SubjectShortName" Type="String" />
                            <asp:Parameter Name="ClassName" Type="String" />
                            <asp:Parameter Name="WeekNumber" Type="Int32" />
                            <asp:Parameter Name="LessonNumber" Type="String" />
                            <asp:Parameter Name="LessonTopic" Type="String" />
                            <asp:Parameter Name="LessonObjectives" Type="String" />
                            <asp:Parameter Name="LessonMethod" Type="String" />
                            <asp:Parameter Name="LessonHomework" Type="String" />
                            <asp:Parameter Name="Remark" Type="String" />
                            <asp:Parameter Name="Remark2" Type="String" />
                            <asp:Parameter Name="Remark3" Type="String" />
                        </InsertParameters>
                    </asp:SqlDataSource>
        <asp:SqlDataSource ID="dsSqlSubjects" runat="server" ConnectionString="<%$ ConnectionStrings:iTecon %>"                        
                        SelectCommand="">
        </asp:SqlDataSource>
                    <asp:SqlDataSource ID="dsSqlSubjectsAdd_Edit" runat="server" ConnectionString="<%$ ConnectionStrings:iTecon %>" 
                        SelectCommand="SELECT [ShortName], [SubjectName] FROM [TEMPSubject] WHERE ([SubjectId] = @SubjectId) ORDER BY [SubjectName]">
                        <SelectParameters>
                            <asp:ControlParameter ControlID="gvMaster" Name="SubjectId" 
                                PropertyName="SelectedValue" Type="Int32" />
                        </SelectParameters>
                    </asp:SqlDataSource>
                    <asp:SqlDataSource ID="dsSqlClassesAdd_Edit" runat="server" 
                        ConnectionString="<%$ ConnectionStrings:iTecon %>" 
                        SelectCommand="SELECT [ClassName] FROM [TEMPClass] WHERE ([ClassName] = @ClassName) ORDER BY [ClassName]">
                        <SelectParameters>
                            <asp:ControlParameter ControlID="gvMaster" Name="ClassName" 
                                PropertyName="SelectedDataKey(1)" Type="String" />
                        </SelectParameters>
                    </asp:SqlDataSource>
                    <asp:ObjectDataSource ID="dsObjSerialNumbers" runat="server" 
                                            SelectMethod="GetIntegerSeries" TypeName="Common">
                        <SelectParameters>
                            <asp:Parameter DefaultValue="1" Name="minimum" Type="Int32" />
                            <asp:Parameter DefaultValue="20" Name="maximum" Type="Int32" />
                            <asp:Parameter DefaultValue="1" Name="interval" Type="Int32" />
                        </SelectParameters>
                    </asp:ObjectDataSource>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    &nbsp;</td>
            </tr>
        </table>
    
    </div>
    </form>
</body>
</html>
