<%@ Page Language="VB" AutoEventWireup="false" CodeFile="managehospitals.aspx.vb" Inherits="modules_system_setups_metadata_managehospitals" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head id="Head1" runat="server">
    <title>Untitled Page</title>
    <link href="../../../../../StyleSheet.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <form id="form1" runat="server">
    <div>
        <table border="0" width="100%">
            <tr>
                <td colspan="2">
                    <asp:Label ID="lblHeader" runat="server" Font-Bold="True" Font-Size="Small" 
                        Text=":: Manage Existing Hospitals"></asp:Label></td>
            </tr>
            <tr>
                <td width="3%">
                    &nbsp;</td>
                <td>
                    <asp:GridView ID="gvUsers" runat="server" AllowSorting="True" AutoGenerateColumns="False"
                        AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True"
                        CssClass="noBorderedMenuTable" DataKeyNames="HospitalId" 
                        DataSourceID="dsSqlGetData" Width="2500px" CellPadding="4" ForeColor="#333333" 
                        GridLines="None" 
                        
                        EmptyDataText="&amp;nbsp;&lt;br /&gt;No records to display.&lt;br /&gt;&amp;nbsp;">
                        <Columns>
                            <asp:BoundField DataField="HospitalId" HeaderText="Id"
                                SortExpression="HospitalId" InsertVisible="False" ReadOnly="True" />
                            <asp:TemplateField HeaderText="Hospital Code" SortExpression="HospitalCode">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TextBox1" runat="server" Columns="20" 
                                        Text='<%# Bind("HospitalCode") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label1" runat="server" Text='<%# Bind("HospitalCode") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Hospital Name" SortExpression="HospitalName">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TextBox2" runat="server" Columns="40" 
                                        Text='<%# Bind("HospitalName") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label2" runat="server" Text='<%# Bind("HospitalName") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Doctors-in-Charge" 
                                SortExpression="DoctorsInCharge">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TextBox3" runat="server" Columns="40" 
                                        Text='<%# Bind("DoctorsInCharge") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label3" runat="server" Text='<%# Bind("DoctorsInCharge") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Email" SortExpression="Email">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TextBox4" runat="server" Columns="40" 
                                        Text='<%# Bind("Email") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label4" runat="server" Text='<%# Bind("Email") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Website" SortExpression="Website">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TextBox5" runat="server" Columns="40" 
                                        Text='<%# Bind("Website") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label5" runat="server" Text='<%# Bind("Website") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Hospital Address 1" 
                                SortExpression="HospitalAddress1">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TextBox6" runat="server" Columns="30" Rows="3" 
                                        Text='<%# Bind("HospitalAddress1") %>' TextMode="MultiLine" 
                                        CssClass="defaultFormElementStyle"></asp:TextBox>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label6" runat="server" Text='<%# Bind("HospitalAddress1") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Telephones 1" SortExpression="Telephones1">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TextBox7" runat="server" Columns="40" 
                                        Text='<%# Bind("Telephones1") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label7" runat="server" Text='<%# Bind("Telephones1") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Hospital Address 2" 
                                SortExpression="HospitalAddress2">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TextBox8" runat="server" Columns="30" Rows="3" 
                                        Text='<%# Bind("HospitalAddress2") %>' TextMode="MultiLine" 
                                        CssClass="defaultFormElementStyle"></asp:TextBox>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label8" runat="server" Text='<%# Bind("HospitalAddress2") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Telephones 2" SortExpression="Telephones2">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TextBox9" runat="server" Columns="40" 
                                        Text='<%# Bind("Telephones2") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label9" runat="server" Text='<%# Bind("Telephones2") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Hospital Address 3" 
                                SortExpression="HospitalAddress3">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TextBox10" runat="server" Columns="30" Rows="3" 
                                        Text='<%# Bind("HospitalAddress3") %>' TextMode="MultiLine" 
                                        CssClass="defaultFormElementStyle"></asp:TextBox>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label10" runat="server" Text='<%# Bind("HospitalAddress3") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Telephones 3" SortExpression="Telephones3">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TextBox11" runat="server" Columns="40" 
                                        Text='<%# Bind("Telephones3") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label11" runat="server" Text='<%# Bind("Telephones3") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Hospital Address 4" 
                                SortExpression="HospitalAddress4">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TextBox12" runat="server" Columns="30" Rows="3" 
                                        Text='<%# Bind("HospitalAddress4") %>' TextMode="MultiLine" 
                                        CssClass="defaultFormElementStyle"></asp:TextBox>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label12" runat="server" Text='<%# Bind("HospitalAddress4") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Telephones 4" SortExpression="Telephones4">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TextBox13" runat="server" Columns="40" 
                                        Text='<%# Bind("Telephones4") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label13" runat="server" Text='<%# Bind("Telephones4") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Hospital Address 5" 
                                SortExpression="HospitalAddress5">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TextBox14" runat="server" Columns="30" Rows="3" 
                                        Text='<%# Bind("HospitalAddress5") %>' TextMode="MultiLine" 
                                        CssClass="defaultFormElementStyle"></asp:TextBox>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label14" runat="server" Text='<%# Bind("HospitalAddress5") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Telephones 5" SortExpression="Telephones5">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TextBox15" runat="server" Columns="40" 
                                        Text='<%# Bind("Telephones5") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label15" runat="server" Text='<%# Bind("Telephones5") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:BoundField DataField="Remark" HeaderText="Remark" 
                                SortExpression="Remark" Visible="False" />
                        </Columns>
                        <RowStyle HorizontalAlign="Left" VerticalAlign="Top" BackColor="#FFFBD6" 
                            ForeColor="#333333" />
                        <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" 
                            HorizontalAlign="Left" VerticalAlign="Top" />
                        <EditRowStyle CssClass="defaultFormElementStyle" />
                        <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                        <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
                        <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="Navy" />
                        <AlternatingRowStyle BackColor="White" />
                    </asp:GridView>
                    <asp:SqlDataSource ID="dsSqlGetData" runat="server" ConnectionString="<%$ ConnectionStrings:iTecon %>"
                        SelectCommand="STP_HR_SELECTALL_HR_Hospital" 
                        DeleteCommand="STP_HR_DELETE_HR_Hospital" 
                        DeleteCommandType="StoredProcedure" 
                        InsertCommand="STP_HR_INSERT_HR_Hospital" 
                        InsertCommandType="StoredProcedure" SelectCommandType="StoredProcedure" 
                        UpdateCommand="STP_HR_UPDATE_HR_Hospital" 
                        UpdateCommandType="StoredProcedure">
                        <DeleteParameters>
                            <asp:Parameter Name="HospitalId" Type="Int32" />
                        </DeleteParameters>
                        <UpdateParameters>
                            <asp:Parameter Name="HospitalId" Type="Int32" />
                            <asp:Parameter Name="HospitalCode" Type="String" />
                            <asp:Parameter Name="HospitalName" Type="String" />
                            <asp:Parameter Name="DoctorsInCharge" Type="String" />
                            <asp:Parameter Name="HospitalAddress1" Type="String" />
                            <asp:Parameter Name="Telephones1" Type="String" />
                            <asp:Parameter Name="HospitalAddress2" Type="String" />
                            <asp:Parameter Name="Telephones2" Type="String" />
                            <asp:Parameter Name="HospitalAddress3" Type="String" />
                            <asp:Parameter Name="Telephones3" Type="String" />
                            <asp:Parameter Name="HospitalAddress4" Type="String" />
                            <asp:Parameter Name="Telephones4" Type="String" />
                            <asp:Parameter Name="HospitalAddress5" Type="String" />
                            <asp:Parameter Name="Telephones5" Type="String" />
                            <asp:Parameter Name="Email" Type="String" />
                            <asp:Parameter Name="Website" Type="String" />
                            <asp:Parameter Name="Remark" Type="String" />
                        </UpdateParameters>
                        <InsertParameters>
                            <asp:Parameter Direction="InputOutput" Name="HospitalId" Type="Int32" />
                            <asp:Parameter Name="HospitalCode" Type="String" />
                            <asp:Parameter Name="HospitalName" Type="String" />
                            <asp:Parameter Name="DoctorsInCharge" Type="String" />
                            <asp:Parameter Name="HospitalAddress1" Type="String" />
                            <asp:Parameter Name="Telephones1" Type="String" />
                            <asp:Parameter Name="HospitalAddress2" Type="String" />
                            <asp:Parameter Name="Telephones2" Type="String" />
                            <asp:Parameter Name="HospitalAddress3" Type="String" />
                            <asp:Parameter Name="Telephones3" Type="String" />
                            <asp:Parameter Name="HospitalAddress4" Type="String" />
                            <asp:Parameter Name="Telephones4" Type="String" />
                            <asp:Parameter Name="HospitalAddress5" Type="String" />
                            <asp:Parameter Name="Telephones5" Type="String" />
                            <asp:Parameter Name="Email" Type="String" />
                            <asp:Parameter Name="Website" Type="String" />
                            <asp:Parameter Name="Remark" Type="String" />
                        </InsertParameters>
                    </asp:SqlDataSource>
                </td>
            </tr>
            <tr>
                <td>
                </td>
                <td>
                    <hr color="black" />
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <br />
                    <asp:Label ID="lblAddNew" runat="server" Font-Bold="True" Font-Size="Small" 
                        Text=":: Add a New Hospital"></asp:Label></td>
            </tr>
            <tr>
                <td>
                    &nbsp;</td>
                <td><asp:DetailsView ID="DetailsView1" runat="server" AutoGenerateRows="False" DataKeyNames="HospitalId"
                        DataSourceID="dsSqlGetData" DefaultMode="Insert" Width="600px" 
                        CellPadding="4" ForeColor="#333333" GridLines="None" 
                        AutoGenerateInsertButton="True">
                        <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                        <CommandRowStyle BackColor="#FFFFC0" Font-Bold="True" />
                        <RowStyle HorizontalAlign="Left" VerticalAlign="Top" Wrap="True" 
                            BackColor="#FFFBD6" ForeColor="#333333" />
                        <FieldHeaderStyle BackColor="#FFFF99" Font-Bold="True" Width="180px" />
                        <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
                        <Fields>
                            <asp:BoundField DataField="HospitalId" HeaderText="HospitalId" 
                                InsertVisible="False" ReadOnly="True"
                                SortExpression="HospitalId" />
                            <asp:TemplateField HeaderText="Hospital Code:" SortExpression="HospitalCode">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TextBox1" runat="server" Text='<%# Bind("HospitalCode") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <InsertItemTemplate>
                                    <asp:TextBox ID="TextBox1" runat="server" Columns="20" 
                                        Text='<%# Bind("HospitalCode") %>'></asp:TextBox>
                                </InsertItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label1" runat="server" Text='<%# Bind("HospitalCode") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Hospital Name:" SortExpression="HospitalName">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TextBox2" runat="server" Text='<%# Bind("HospitalName") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <InsertItemTemplate>
                                    <asp:TextBox ID="TextBox2" runat="server" Columns="40" 
                                        Text='<%# Bind("HospitalName") %>'></asp:TextBox>
                                </InsertItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label2" runat="server" Text='<%# Bind("HospitalName") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Doctors-in-Charge:" 
                                SortExpression="DoctorsInCharge">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TextBox3" runat="server" Text='<%# Bind("DoctorsInCharge") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <InsertItemTemplate>
                                    <asp:TextBox ID="TextBox3" runat="server" Columns="40" 
                                        Text='<%# Bind("DoctorsInCharge") %>'></asp:TextBox>
                                    <br />
                                    Please separate multiple doctors&#39; names with commas.
                                </InsertItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label3" runat="server" Text='<%# Bind("DoctorsInCharge") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Email:" SortExpression="Email">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TextBox4" runat="server" Text='<%# Bind("Email") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <InsertItemTemplate>
                                    <asp:TextBox ID="TextBox4" runat="server" Columns="40" 
                                        Text='<%# Bind("Email") %>'></asp:TextBox>
                                    <br />
                                    Please separate multiple email addresses with commas.
                                </InsertItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label4" runat="server" Text='<%# Bind("Email") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Website:" SortExpression="Website">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TextBox5" runat="server" Text='<%# Bind("Website") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <InsertItemTemplate>
                                    <asp:TextBox ID="TextBox5" runat="server" Columns="40" 
                                        Text='<%# Bind("Website") %>'></asp:TextBox>
                                </InsertItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label5" runat="server" Text='<%# Bind("Website") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Hospital Address 1:" 
                                SortExpression="HospitalAddress1">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TextBox6" runat="server" 
                                        Text='<%# Bind("HospitalAddress1") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <InsertItemTemplate>
                                    <asp:TextBox ID="TextBox6" runat="server" Columns="50" Rows="3" 
                                        Text='<%# Bind("HospitalAddress1") %>' TextMode="MultiLine" 
                                        CssClass="defaultFormElementStyle"></asp:TextBox>
                                </InsertItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label6" runat="server" Text='<%# Bind("HospitalAddress1") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Telephones 1:" SortExpression="Telephones1">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TextBox7" runat="server" Text='<%# Bind("Telephones1") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <InsertItemTemplate>
                                    <asp:TextBox ID="TextBox7" runat="server" Columns="40" 
                                        Text='<%# Bind("Telephones1") %>'></asp:TextBox>
                                    <br />
                                    Please separate multiple telephone numbers with commas.
                                </InsertItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label7" runat="server" Text='<%# Bind("Telephones1") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Hospital Address 2:" 
                                SortExpression="HospitalAddress2">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TextBox8" runat="server" 
                                        Text='<%# Bind("HospitalAddress2") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <InsertItemTemplate>
                                    <asp:TextBox ID="TextBox8" runat="server" Columns="50" Rows="3" 
                                        Text='<%# Bind("HospitalAddress2") %>' TextMode="MultiLine" 
                                        CssClass="defaultFormElementStyle"></asp:TextBox>
                                </InsertItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label8" runat="server" Text='<%# Bind("HospitalAddress2") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Telephones 2:" SortExpression="Telephones2">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TextBox9" runat="server" Text='<%# Bind("Telephones2") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <InsertItemTemplate>
                                    <asp:TextBox ID="TextBox9" runat="server" Columns="40" 
                                        Text='<%# Bind("Telephones2") %>'></asp:TextBox>
                                    <br />
                                    Please separate multiple telephone numbers with commas.
                                </InsertItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label9" runat="server" Text='<%# Bind("Telephones2") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Hospital Address 3:" 
                                SortExpression="HospitalAddress3">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TextBox10" runat="server" 
                                        Text='<%# Bind("HospitalAddress3") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <InsertItemTemplate>
                                    <asp:TextBox ID="TextBox10" runat="server" Columns="50" Rows="3" 
                                        Text='<%# Bind("HospitalAddress3") %>' TextMode="MultiLine" 
                                        CssClass="defaultFormElementStyle"></asp:TextBox>
                                </InsertItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label10" runat="server" Text='<%# Bind("HospitalAddress3") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Telephones 3:" SortExpression="Telephones3">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TextBox11" runat="server" Text='<%# Bind("Telephones3") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <InsertItemTemplate>
                                    <asp:TextBox ID="TextBox11" runat="server" Columns="40" 
                                        Text='<%# Bind("Telephones3") %>'></asp:TextBox>
                                    <br />
                                    Please separate multiple telephone numbers with commas.
                                </InsertItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label11" runat="server" Text='<%# Bind("Telephones3") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Hospital Address 4:" 
                                SortExpression="HospitalAddress4">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TextBox12" runat="server" 
                                        Text='<%# Bind("HospitalAddress4") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <InsertItemTemplate>
                                    <asp:TextBox ID="TextBox12" runat="server" Columns="50" Rows="3" 
                                        Text='<%# Bind("HospitalAddress4") %>' TextMode="MultiLine" 
                                        CssClass="defaultFormElementStyle"></asp:TextBox>
                                </InsertItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label12" runat="server" Text='<%# Bind("HospitalAddress4") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Telephones 4:" SortExpression="Telephones4">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TextBox13" runat="server" Text='<%# Bind("Telephones4") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <InsertItemTemplate>
                                    <asp:TextBox ID="TextBox13" runat="server" Columns="40" 
                                        Text='<%# Bind("Telephones4") %>'></asp:TextBox>
                                    <br />
                                    Please separate multiple telephone numbers with commas.
                                </InsertItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label13" runat="server" Text='<%# Bind("Telephones4") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Hospital Address 5:" 
                                SortExpression="HospitalAddress5">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TextBox14" runat="server" 
                                        Text='<%# Bind("HospitalAddress5") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <InsertItemTemplate>
                                    <asp:TextBox ID="TextBox14" runat="server" Columns="50" Rows="3" 
                                        Text='<%# Bind("HospitalAddress5") %>' TextMode="MultiLine" 
                                        CssClass="defaultFormElementStyle"></asp:TextBox>
                                </InsertItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label14" runat="server" Text='<%# Bind("HospitalAddress5") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Telephones 5:" SortExpression="Telephones5">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TextBox15" runat="server" Text='<%# Bind("Telephones5") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <InsertItemTemplate>
                                    <asp:TextBox ID="TextBox15" runat="server" Columns="40" 
                                        Text='<%# Bind("Telephones5") %>'></asp:TextBox>
                                    <br />
                                    Please separate multiple telephone numbers with commas.
                                </InsertItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label15" runat="server" Text='<%# Bind("Telephones5") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Remark:" SortExpression="Remark">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TextBox16" runat="server" Text='<%# Bind("Remark") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <InsertItemTemplate>
                                    <asp:TextBox ID="TextBox16" runat="server" Columns="60" Rows="5" 
                                        Text='<%# Bind("Remark") %>' TextMode="MultiLine" 
                                        CssClass="defaultFormElementStyle"></asp:TextBox>
                                </InsertItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label16" runat="server" Text='<%# Bind("Remark") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                        </Fields>
                        <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                        <AlternatingRowStyle BackColor="White" />
                    </asp:DetailsView>
                &nbsp;&nbsp;&nbsp;</td>
            </tr>
            <tr>
                <td colspan="2">
                    &nbsp;</td>
            </tr>
        </table>
    
    </div>
    </form>
</body>
</html>
