<%@ Page Language="VB" Strict="false" AutoEventWireup="false" CodeFile="managenoticeboard.aspx.vb" Inherits="modules_system_setups_metadata_managenoticeboard" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head id="Head1" runat="server">
    <title>Untitled Page</title>
    <link href="../../../../../StyleSheet.css" rel="stylesheet" type="text/css" />
<script language="javascript" type="text/javascript">
// <!CDATA[

function TABLE1_onclick() {

}

// ]]>
</script>
</head>
<body>
    <form id="form1" runat="server">
    <div>
        <table width="100%"  border="0" id="TABLE1" onclick="return TABLE1_onclick()">
          <tr>
            <td colspan="2"><asp:Label ID="lblHeader" runat="server" Text=":: Manage Existing Announcements" Font-Bold="True" Font-Size="Small"></asp:Label>&nbsp;(most 
                recent first)</td>
          </tr>
          <tr>
            <td width="3%">&nbsp;</td>
            <td>
        <asp:GridView ID="gvUsers" runat="server" CssClass="noBorderedMenuTable" 
                    AutoGenerateColumns="False" AutoGenerateDeleteButton="True" 
                    AutoGenerateEditButton="True" AutoGenerateSelectButton="True" PageSize="30" 
                    DataKeyNames="AnnouncementId" DataSourceID="dsoAnnouncements" AllowSorting="True" 
                    CellPadding="4" ForeColor="#333333" GridLines="None" Width="1000px" >
            <Columns>
                <asp:BoundField DataField="AnnouncementId" HeaderText="Id" 
                    InsertVisible="False" ReadOnly="True" SortExpression="AnnouncementId">
                <HeaderStyle HorizontalAlign="Left" />
                <ItemStyle Width="5%" />
                </asp:BoundField>
                <asp:TemplateField HeaderText="Date Published" SortExpression="DatePublished">
                    <EditItemTemplate>
                        <asp:Label ID="Label1" runat="server" Text='<%# Bind("DatePublished") %>'></asp:Label>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label3" runat="server" Text='<%# FormatDateTime(DataBinder.Eval(Container.DataItem, "DatePublished"), DateFormat.LongDate) & " " & FormatDateTime(DataBinder.Eval(Container.DataItem, "DatePublished"), DateFormat.ShortTime) %>'></asp:Label>
                    </ItemTemplate>
                    <HeaderStyle HorizontalAlign="Left" />
                    <ItemStyle Width="20%" />
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Message" SortExpression="Message">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox1" runat="server" Columns="100" 
                            CssClass="defaultFormElementStyle" Rows="5" Text='<%# Bind("Message") %>' 
                            TextMode="MultiLine"></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label1" runat="server" Text='<%# Bind("Message") %>'></asp:Label>
                    </ItemTemplate>
                    <HeaderStyle HorizontalAlign="Left" />
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Expired?" SortExpression="Expired">
                    <EditItemTemplate>
                        <asp:DropDownList ID="DropDownList1" runat="server" 
                            CssClass="defaultFormElementStyle" SelectedValue='<%# Bind("Expired") %>'>
                            <asp:ListItem Value="N">No</asp:ListItem>
                            <asp:ListItem Value="Y">Yes</asp:ListItem>
                        </asp:DropDownList>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label2" runat="server" Text='<%# Bind("Expired") %>'></asp:Label>
                    </ItemTemplate>
                    <HeaderStyle HorizontalAlign="Left" />
                    <ItemStyle Width="10%" />
                </asp:TemplateField>
            </Columns>
            <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
            <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="Navy" />
            <RowStyle HorizontalAlign="Left" VerticalAlign="Top" BackColor="#FFFBD6" 
                ForeColor="#333333" />
            <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
            <EditRowStyle CssClass="defaultFormElementStyle" />
            <AlternatingRowStyle BackColor="White" />
        </asp:GridView>
        <asp:SqlDataSource ID="dsoAnnouncements" runat="server" ConnectionString="<%$ ConnectionStrings:iTecon %>"
            DeleteCommand="STP_METADATA_DELETE_TEMPAnnouncements" DeleteCommandType="StoredProcedure"
            InsertCommand="STP_METADATA_INSERT_TEMPAnnouncements" InsertCommandType="StoredProcedure"
            SelectCommand="STP_METADATA_SELECTALL_TEMPAnnouncements" SelectCommandType="StoredProcedure"
            UpdateCommand="STP_METADATA_UPDATE_TEMPAnnouncements" 
                    UpdateCommandType="StoredProcedure">
            <DeleteParameters>
                <asp:Parameter Name="AnnouncementId" Type="Int32" />
            </DeleteParameters>
            <UpdateParameters>
                <asp:Parameter Name="AnnouncementId" Type="Int32" />
                <asp:Parameter Name="DatePublished" Type="DateTime" />
                <asp:Parameter Name="Message" Type="String" />
                <asp:Parameter Name="Expired" Type="String" />
            </UpdateParameters>
            <InsertParameters>
                <asp:Parameter Name="AnnouncementId" Type="Int32" Direction="InputOutput" />
                <asp:Parameter Name="DatePublished" Type="DateTime" />
                <asp:Parameter Name="Message" Type="String" />
                <asp:Parameter Name="Expired" Type="String" />
            </InsertParameters>
        </asp:SqlDataSource>
        &nbsp;</td>
          </tr>
            <tr>
                <td>
                </td>
                <td>
        <hr color="black" />
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <br />
        <asp:Label ID="Label9" runat="server" Font-Bold="True" Font-Size="Small" Text=":: Create a New Announcement"></asp:Label></td>
            </tr>
          <tr>
            <td>&nbsp;</td>
            <td>
        <asp:DetailsView ID="DetailsView1" runat="server" AutoGenerateRows="False"
            DataKeyNames="AnnouncementId" DataSourceID="dsoAnnouncements" Height="50px" 
                    CssClass="noBorderedMenuTable" DefaultMode="Insert" CellPadding="4" 
                    ForeColor="#333333" GridLines="None" Width="800px">
            <FieldHeaderStyle BackColor="#FFFF99" Font-Bold="True" Width="180px" />
            <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
            <Fields>
                <asp:BoundField DataField="AnnouncementId" HeaderText="AnnouncementId" 
                    SortExpression="AnnouncementId" InsertVisible="False" ReadOnly="True">
                </asp:BoundField>
                <asp:TemplateField HeaderText="Date Published:" SortExpression="DatePublished" 
                    Visible="False">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox3" runat="server" Text='<%# Bind("DatePublished") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <InsertItemTemplate>
                        <asp:Calendar ID="Calendar1" runat="server" BackColor="White" 
                            BorderColor="#999999" CellPadding="4" CssClass="defaultFormElementStyle" 
                            DayNameFormat="Shortest" Font-Names="Verdana" Font-Size="8pt" ForeColor="Black" 
                            Height="180px" SelectedDate='<%# Bind("DatePublished") %>' Width="200px">
                            <SelectedDayStyle BackColor="#666666" Font-Bold="True" ForeColor="White" />
                            <SelectorStyle BackColor="#CCCCCC" />
                            <WeekendDayStyle BackColor="#FFFFCC" />
                            <TodayDayStyle BackColor="#CCCCCC" ForeColor="Black" />
                            <OtherMonthDayStyle ForeColor="#808080" />
                            <NextPrevStyle VerticalAlign="Bottom" />
                            <DayHeaderStyle BackColor="#CCCCCC" Font-Bold="True" Font-Size="7pt" />
                            <TitleStyle BackColor="#999999" BorderColor="Black" Font-Bold="True" />
                        </asp:Calendar>
                    </InsertItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label3" runat="server" Text='<%# Bind("DatePublished") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Message:" SortExpression="Message">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox2" runat="server" Text='<%# Bind("Message") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <InsertItemTemplate>
                        <asp:TextBox ID="TextBox2" runat="server" Text='<%# Bind("Message") %>' 
                            Columns="100" CssClass="defaultFormElementStyle" Rows="10" TextMode="MultiLine"></asp:TextBox>
                    </InsertItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label2" runat="server" Text='<%# Bind("Message") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Expired?" SortExpression="Expired">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox1" runat="server" Text='<%# Bind("Expired") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <InsertItemTemplate>
                        <asp:DropDownList ID="DropDownList2" runat="server" 
                            CssClass="defaultFormElementStyle" SelectedValue='<%# Bind("Expired") %>'>
                            <asp:ListItem Value="N">No</asp:ListItem>
                            <asp:ListItem Value="Y">Yes</asp:ListItem>
                        </asp:DropDownList>
                    </InsertItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label1" runat="server" Text='<%# Bind("Expired") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:CommandField ShowInsertButton="True" />
            </Fields>
            <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
            <EditRowStyle Wrap="True" />
            <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
            <CommandRowStyle BackColor="#FFFFC0" Font-Bold="True" />
            <RowStyle Wrap="True" HorizontalAlign="Left" VerticalAlign="Top" 
                BackColor="#FFFBD6" ForeColor="#333333" />
            <AlternatingRowStyle BackColor="White" />
        </asp:DetailsView>
                &nbsp; &nbsp;</td>
          </tr>
          <tr>
            <td colspan="2">&nbsp;</td>
          </tr>
      </table>
      </div>
    </form>
</body>
</html>
