<%@ Page Language="VB" AutoEventWireup="false" CodeFile="managestates.aspx.vb" Inherits="modules_system_setups_metadata_managestates" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head runat="server">
    <title>Untitled Page</title>
    <link href="../../../../../StyleSheet.css" rel="stylesheet" type="text/css" />
    <style type="text/css">
        .style1
        {
            width: 100px;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
    <div>
        <table border="0" width="100%">
            <tr>
                <td colspan="2" style="height: 18px">
                    <asp:Label ID="lblHeader" runat="server" Font-Bold="True" Font-Size="Small" Text=":: Manage States"></asp:Label></td>
            </tr>
            <tr>
                <td width="3%">
                    &nbsp;</td>
                <td>
                    <table>
                        <tr>
                            <td style="width: 333px">
                                <asp:Label ID="Label5" runat="server" Font-Bold="True" Font-Size="Small" Text=":: Manage Existing States"></asp:Label></td>
                            <td valign="top" class="style1">
                            </td>
                            <td style="width: 250px" valign="top">
                                <asp:Label ID="Label4" runat="server" Font-Bold="True" Font-Size="Small" Text=":: Create a New State"></asp:Label></td>
                        </tr>
                        <tr>
                            <td style="width: 333px">
                                <asp:GridView ID="gvUsers" runat="server" AllowSorting="True" AutoGenerateColumns="False"
                        AutoGenerateEditButton="True" AutoGenerateSelectButton="True" CssClass="noBorderedMenuTable"
                        DataKeyNames="StateId" DataSourceID="dsSqlStates" AutoGenerateDeleteButton="True" 
                                    AllowPaging="True" PageSize="50" CellPadding="4" ForeColor="#333333" 
                                    GridLines="None" Width="600px">
                        <Columns>
                            <asp:TemplateField HeaderText="Id" InsertVisible="False" 
                                SortExpression="StateId">
                                <EditItemTemplate>
                                    <asp:Label ID="Label1" runat="server" Text='<%# Eval("StateId") %>'></asp:Label>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label1" runat="server" Text='<%# Bind("StateId") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="State" SortExpression="StateName">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TextBox1" runat="server" Text='<%# Bind("StateName") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label2" runat="server" Text='<%# Bind("StateName") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Country" SortExpression="CountryName">
                                <EditItemTemplate>
                                    <asp:DropDownList ID="DropDownList1" runat="server" CssClass="defaultFormElementStyle" DataSourceID="dsSqlCountries" DataTextField="CountryName" DataValueField="CountryId" SelectedValue='<%# Bind("CountryId") %>'>
                                    </asp:DropDownList><asp:SqlDataSource ID="dsSqlCountries" runat="server" ConnectionString="<%$ ConnectionStrings:iTecon %>"
                                        SelectCommand="SELECT DISTINCT [CountryId], [CountryName] FROM [Core_Country] ORDER BY [CountryName]">
                                    </asp:SqlDataSource>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label3" runat="server" Text='<%# Bind("CountryName") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                        </Columns>
                        <RowStyle HorizontalAlign="Left" VerticalAlign="Top" BackColor="#FFFBD6" 
                                        ForeColor="#333333" />
                                    <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                        <EditRowStyle CssClass="defaultFormElementStyle" />
                                    <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                                    <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
                        <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="Navy" />
                                    <AlternatingRowStyle BackColor="White" />
                    </asp:GridView>
                                &nbsp;
                            </td>
                            <td valign="top" class="style1">
                                &nbsp;</td>
                            <td style="width: 250px" valign="top">
                    <asp:DetailsView ID="DetailsView1" runat="server" AutoGenerateRows="False" CssClass="noBorderedMenuTable"
                        DataKeyNames="StateId,CountryId1" DataSourceID="dsSqlStates" DefaultMode="Insert"
                        Height="50px" CellPadding="4" ForeColor="#333333" GridLines="None" Width="300px">
                        <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                        <EditRowStyle Wrap="True" />
                        <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                        <CommandRowStyle BackColor="#FFFFC0" Font-Bold="True" />
                        <RowStyle HorizontalAlign="Left" VerticalAlign="Top" Wrap="True" 
                            BackColor="#FFFBD6" ForeColor="#333333" />
                        <FieldHeaderStyle BackColor="#FFFF99" Font-Bold="True" />
                        <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
                        <Fields>
                            <asp:BoundField DataField="StateId" HeaderText="State Id:" 
                                InsertVisible="False" ReadOnly="True"
                                SortExpression="StateId" />
                            <asp:BoundField DataField="StateName" HeaderText="State Name:" 
                                SortExpression="StateName" />
                            <asp:TemplateField HeaderText="Country:" SortExpression="CountryName">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TextBox1" runat="server" Text='<%# Bind("CountryName") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <InsertItemTemplate>
                                    <asp:DropDownList ID="DropDownList2" runat="server" CssClass="defaultFormElementStyle"
                                        DataSourceID="dsSqlCountries" DataTextField="CountryName" DataValueField="CountryId"
                                        SelectedValue='<%# Bind("CountryId") %>'>
                                    </asp:DropDownList><asp:SqlDataSource ID="dsSqlCountries" runat="server" ConnectionString="<%$ ConnectionStrings:iTecon %>"
                                        SelectCommand="SELECT [CountryId], [CountryName] FROM [Core_Country] ORDER BY [CountryName]">
                                    </asp:SqlDataSource>
                                </InsertItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label1" runat="server" Text='<%# Bind("CountryName") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:CommandField ShowInsertButton="True" />
                        </Fields>
                        <AlternatingRowStyle BackColor="White" />
                    </asp:DetailsView>
                    &nbsp;</td>
                        </tr>
                        <tr>
                            <td style="width: 333px">
                            </td>
                            <td class="style1">
                            </td>
                            <td style="width: 250px">
                            </td>
                        </tr>
                    </table>
                    <asp:SqlDataSource ID="dsSqlStates" runat="server" ConnectionString="<%$ ConnectionStrings:iTecon %>"
                        DeleteCommand="STP_METADATA_DELETE_STATE" DeleteCommandType="StoredProcedure"
                        InsertCommand="STP_METADATA_INSERT_STATE" InsertCommandType="StoredProcedure"
                        SelectCommand="STP_METADATA_SELECT_STATE_ALL" SelectCommandType="StoredProcedure"
                        UpdateCommand="STP_METADATA_UPDATE_STATE" UpdateCommandType="StoredProcedure">
                        <DeleteParameters>
                            <asp:Parameter Name="StateId" Type="Int32" />
                        </DeleteParameters>
                        <UpdateParameters>
                            <asp:Parameter Name="StateId" Type="Int32" />
                            <asp:Parameter Name="StateName" Type="String" />
                            <asp:Parameter Name="CountryId" Type="Int32" />
                        </UpdateParameters>
                        <InsertParameters>
                            <asp:Parameter Name="StateName" Type="String" />
                            <asp:Parameter Name="CountryId" Type="Int32" />
                        </InsertParameters>
                    </asp:SqlDataSource>
                    &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</td>
            </tr>
        </table>
    
    </div>
    </form>
</body>
</html>
